package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type group struct {
	category string
	name     string
	items    string
}

type spec struct {
	Name       string
	Category   string
	Group      string
	Template   string
	Confidence float64
}

func main() {
	seen := map[string]bool{}
	specs := []spec{}
	for _, g := range catalog {
		for _, item := range splitItems(g.items) {
			key := strings.ToLower(item)
			if key == "" || seen[key] {
				continue
			}
			seen[key] = true
			specs = append(specs, spec{
				Name:       item,
				Category:   g.category,
				Group:      g.name,
				Template:   inferTemplate(g.category, item),
				Confidence: confidenceFor(g.category),
			})
		}
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	outDir := filepath.Join("internal", "indicators", "generated")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatal(err)
	}
	var b strings.Builder
	b.WriteString("// Code generated by tools/indicator_catalog_gen; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString("func init() {\n")
	b.WriteString("\tSpecs = append(Specs,\n")
	for _, spec := range specs {
		b.WriteString(fmt.Sprintf("\t\tSpec{Name: %q, Category: %q, Group: %q, Template: %q, Confidence: %.2f},\n", spec.Name, spec.Category, spec.Group, spec.Template, spec.Confidence))
	}
	b.WriteString("\t)\n")
	b.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(outDir, "catalog.go"), []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("generated %d indicator specs\n", len(specs))
}

func splitItems(value string) []string {
	parts := strings.Split(value, "|")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			out = append(out, part)
		}
	}
	return out
}

func confidenceFor(category string) float64 {
	switch category {
	case "trend", "momentum", "volume", "volatility", "support_resistance", "channel", "ichimoku", "fibonacci", "statistical", "price_transform", "stop", "divergence", "smart_money", "elliott", "wyckoff":
		return 0.62
	case "breadth", "sentiment", "order_flow", "options", "crypto_onchain":
		return 0.0
	default:
		return 0.55
	}
}

func inferTemplate(category, name string) string {
	n := normalize(name)
	switch category {
	case "trend":
		if hasAny(n, "moving average", "sma", "ema", "wma", "dema", "tema", "trima", "kama", "mama", "fama", "hma", "vwma", "vidya", "alma", "zlema", "lsma", "mcginley", "jurik", "jma", "smma", "rma", "wilders", "frama", "gaussian", "t3", "tilson") {
			return "moving_average"
		}
		return "trend"
	case "momentum":
		return "momentum"
	case "volume":
		return "volume"
	case "volatility":
		return "volatility"
	case "support_resistance":
		return "support_resistance"
	case "channel":
		return "channel"
	case "bill_williams":
		if hasAny(n, "awesome", "accelerator", "gator") {
			return "momentum"
		}
		return "trend"
	case "cycle":
		return "cycle"
	case "breadth":
		return "breadth"
	case "sentiment":
		return "sentiment"
	case "order_flow":
		return "order_flow"
	case "market_profile":
		if hasAny(n, "volume profile", "poc", "value area", "vah", "val", "vwap", "hvn", "lvn") {
			return "support_resistance"
		}
		return "market_profile_external"
	case "ichimoku":
		return "trend"
	case "gann":
		return "gann"
	case "fibonacci":
		return "fibonacci"
	case "statistical":
		return "statistical"
	case "price_transform":
		return "price_transform"
	case "stop":
		return "stop"
	case "divergence":
		return "divergence"
	case "smart_money":
		return "smart_money"
	case "elliott":
		return "elliott"
	case "wyckoff":
		return "wyckoff"
	case "demark":
		return "momentum"
	case "crypto_onchain":
		if hasAny(n, "funding", "open interest", "long short", "taker") {
			return "sentiment"
		}
		return "crypto_onchain"
	case "options":
		return "options"
	case "renko_kagi_pnf":
		return "renko_kagi_pnf"
	case "heikin_ashi":
		return "heikin_ashi"
	case "session_time":
		return "session_time"
	case "risk_performance":
		return "risk_performance"
	case "pattern_recognition":
		return "pattern_recognition"
	case "ta_lib":
		return inferTalibTemplate(n)
	default:
		if hasAny(n, "volume") {
			return "volume"
		}
		if hasAny(n, "volatility", "atr", "range") {
			return "volatility"
		}
		if hasAny(n, "zig zag", "fractal", "projection") {
			return "trend"
		}
		return "generic"
	}
}

func inferTalibTemplate(name string) string {
	if hasAny(name, "adx", "adxr", "apo", "aroon", "bop", "cci", "cmo", "dx", "macd", "mfi", "mom", "ppo", "roc", "rsi", "stoch", "trix", "ultosc", "willr") {
		return "momentum"
	}
	if hasAny(name, "ad", "adosc", "obv") {
		return "volume"
	}
	if hasAny(name, "atr", "natr", "trange") {
		return "volatility"
	}
	if hasAny(name, "beta", "correl", "linearreg", "stddev", "var") {
		return "statistical"
	}
	if hasAny(name, "avgprice", "medprice", "typprice", "wclprice") {
		return "price_transform"
	}
	if hasAny(name, "ht_") {
		return "cycle"
	}
	return "moving_average"
}

func normalize(value string) string {
	value = strings.ToLower(value)
	value = strings.ReplaceAll(value, "-", " ")
	value = strings.ReplaceAll(value, "_", " ")
	value = strings.ReplaceAll(value, "%", " percent ")
	value = regexp.MustCompile(`\s+`).ReplaceAllString(value, " ")
	return strings.TrimSpace(value)
}

func hasAny(value string, needles ...string) bool {
	for _, needle := range needles {
		if strings.Contains(value, needle) {
			return true
		}
	}
	return false
}

var catalog = []group{
	{"trend", "trend_indikatorleri", "Simple Moving Average|SMA|Exponential Moving Average|EMA|Weighted Moving Average|WMA|Double Exponential Moving Average|DEMA|Triple Exponential Moving Average|TEMA|Triangular Moving Average|TRIMA|Kaufman Adaptive Moving Average|KAMA|MESA Adaptive Moving Average|MAMA|Following Adaptive Moving Average|FAMA|Hull Moving Average|HMA|Volume Weighted Moving Average|VWMA|Variable Index Dynamic Average|VIDYA|Arnaud Legoux Moving Average|ALMA|Zero Lag Exponential Moving Average|ZLEMA|Least Squares Moving Average|LSMA|Linear Regression Moving Average|McGinley Dynamic|Jurik Moving Average|JMA|Smoothed Moving Average|SMMA|Running Moving Average|RMA|Wilders Moving Average|Adaptive Moving Average|Fractal Adaptive Moving Average|FRAMA|Gaussian Moving Average|T3 Moving Average|Tilson T3|Moving Average Ribbon|Moving Average Envelope|Moving Average Channel|Golden Cross|Death Cross|MACD|Moving Average Convergence Divergence|MACD Signal Line|MACD Histogram|Percentage Price Oscillator|PPO|Absolute Price Oscillator|APO|Directional Movement Index|DMI|Average Directional Index|ADX|Positive Directional Indicator|+DI|Negative Directional Indicator|-DI|Aroon Indicator|Aroon Up|Aroon Down|Aroon Oscillator|Parabolic SAR|PSAR|Supertrend|SuperTrend AI|Ichimoku Kinko Hyo|Tenkan-sen|Kijun-sen|Senkou Span A|Senkou Span B|Chikou Span|Kumo Cloud|Donchian Channel|Price Channel|Trend Magic|Chandelier Exit|Vortex Indicator|VI+|VI-|Mass Index|QStick|Guppy Multiple Moving Average|GMMA|Linear Regression Trendline|Linear Regression Channel|Moving Average Slope|Trend Intensity Index|TII|Schaff Trend Cycle|STC|Vertical Horizontal Filter|VHF|Coral Trend Indicator|StepMA"},
	{"momentum", "momentum_oscillator_indikatorleri", "Relative Strength Index|RSI|Stochastic Oscillator|Stochastic %K|Stochastic %D|Slow Stochastic|Fast Stochastic|Stochastic RSI|StochRSI|Commodity Channel Index|CCI|Williams Percent Range|Williams %R|Rate of Change|ROC|Momentum|Money Flow Index|MFI|True Strength Index|TSI|Ultimate Oscillator|UO|Awesome Oscillator|AO|Accelerator Oscillator|AC|Detrended Price Oscillator|DPO|Chande Momentum Oscillator|CMO|Relative Momentum Index|RMI|Relative Vigor Index|RVI|Know Sure Thing|KST|Connors RSI|CRSI|Elder Ray Index|Bull Power|Bear Power|Fisher Transform|Inverse Fisher Transform|Center of Gravity Oscillator|COG|Dynamic Momentum Index|DMI Oscillator|Pretty Good Oscillator|PGO|Coppock Curve|Balance of Power|BOP|Psychological Line|PSY|DecisionPoint Price Momentum Oscillator|PMO|Squeeze Momentum Indicator|Laguerre RSI|Ergodic Oscillator|Elliott Wave Oscillator|EWO|Bollinger Bands %B|Bollinger Bandwidth Oscillator|Klinger Oscillator|Volume Oscillator|Price Oscillator|Chaikin Oscillator|Trend Trigger Factor|TTF|Woodies CCI"},
	{"volume", "hacim_volume_indikatorleri", "Volume|Volume Moving Average|Volume Oscillator|On Balance Volume|OBV|Accumulation Distribution Line|ADL|Accumulation Distribution Oscillator|Chaikin Money Flow|CMF|Chaikin Oscillator|Money Flow Index|MFI|Volume Price Trend|VPT|Price Volume Trend|Positive Volume Index|PVI|Negative Volume Index|NVI|Ease of Movement|EOM|Elder Force Index|Force Index|Klinger Volume Oscillator|KVO|Volume Rate of Change|VROC|Volume Weighted Average Price|VWAP|Anchored VWAP|AVWAP|Rolling VWAP|Session VWAP|Cumulative Volume Delta|CVD|Delta Volume|Bid Ask Delta|Buy Sell Volume|Up Down Volume|Net Volume|Volume Profile|Fixed Range Volume Profile|Session Volume Profile|Visible Range Volume Profile|VPVR|Point of Control|POC|Volume Point of Control|VPOC|Value Area High|VAH|Value Area Low|VAL|High Volume Node|HVN|Low Volume Node|LVN|Market Facilitation Index|MFI Bill Williams|Twiggs Money Flow|Normalized Volume|Relative Volume|RVOL|Cumulative Volume Index|Demand Index|Intraday Intensity Index|Volume Zone Oscillator|VZO|Money Flow Volume|Volume Flow Indicator|VFI|Developing POC|dPOC|Developing VAH|Developing VAL|Time Price Opportunity POC|TPO POC"},
	{"volatility", "volatilite_indikatorleri", "Average True Range|ATR|True Range|Normalized Average True Range|NATR|Bollinger Bands|Bollinger Bandwidth|Bollinger %B|Keltner Channel|Donchian Channel|Average Daily Range|ADR|Historical Volatility|HV|Chaikin Volatility|Standard Deviation|STDEV|Variance|Volatility Ratio|Relative Volatility Index|RVI Volatility|Ulcer Index|Mass Index|Chandelier Exit|Supertrend|Volatility Stop|VStop|ATR Trailing Stop|Kase DevStop|Bollinger Band Squeeze|TTM Squeeze|Squeeze Momentum Indicator|Parkinson Volatility|Garman Klass Volatility|Rogers Satchell Volatility|Yang Zhang Volatility|Implied Volatility|IV|IV Rank|IV Percentile|VIX|Volatility Index|Volatility Cone|Volatility Skew|Volatility Smile|Choppiness Index|CHOP"},
	{"support_resistance", "support_resistance_indikatorleri", "Pivot Points|Classic Pivot Points|Fibonacci Pivot Points|Woodie Pivot Points|Camarilla Pivot Points|DeMark Pivot Points|Central Pivot Range|CPR|Support Resistance Levels|Auto Support Resistance|Dynamic Support Resistance|Fractal Support Resistance|Swing High Low|Previous Day High|Previous Day Low|Previous Week High|Previous Week Low|Previous Month High|Previous Month Low|Round Numbers|Psychological Levels|Supply Demand Zones|Order Block Zones|Fair Value Gap Zones|Liquidity Zones|Volume Profile Levels|VWAP Bands|Anchored VWAP Levels|Fibonacci Retracement|Fibonacci Extension|Fibonacci Expansion|Fibonacci Projection|Fibonacci Channel|Fibonacci Fan|Fibonacci Arc|Fibonacci Time Zones|Gann Levels|Gann Fan|Gann Box|Gann Square|Murrey Math Lines|Naked Point of Control|NPOC|Virgin Point of Control|VPOC Level"},
	{"channel", "kanal_band_indikatorleri", "Bollinger Bands|Keltner Channel|Donchian Channel|Price Channel|Moving Average Envelope|Standard Error Bands|Linear Regression Channel|Trend Channel|Regression Trend Channel|ATR Channel|STARC Bands|Fractal Chaos Bands|High Low Bands|Projection Bands|Percentage Envelope|VWAP Bands|Ichimoku Cloud|Kumo Cloud|Supertrend Bands|Pivot Bands|Quantile Bands|Gaussian Channel|Raff Regression Channel|Andrews Pitchfork|Schiff Pitchfork|Modified Schiff Pitchfork|Fibonacci Bollinger Bands"},
	{"bill_williams", "bill_williams_indikatorleri", "Alligator|Fractals|Awesome Oscillator|Accelerator Oscillator|Gator Oscillator|Market Facilitation Index|BW MFI|Balance Line|Jaw|Teeth|Lips"},
	{"cycle", "cycle_indikatorleri", "Hilbert Transform Dominant Cycle Period|HT_DCPERIOD|Hilbert Transform Dominant Cycle Phase|HT_DCPHASE|Hilbert Transform Phasor Components|HT_PHASOR|Hilbert Transform SineWave|HT_SINE|Hilbert Transform Trendline|HT_TRENDLINE|Hilbert Transform Trend Mode|HT_TRENDMODE|MESA Adaptive Moving Average|MAMA|SineWave Indicator|Cyber Cycle|Center of Gravity|Ehlers Fisher Transform|Ehlers Instantaneous Trendline|Ehlers Roofing Filter|Ehlers Super Smoother|Ehlers MESA Stochastic|Dominant Cycle|Cycle Period|Cycle Phase|Decycler Oscillator"},
	{"breadth", "market_breadth_indikatorleri", "Advance Decline Line|AD Line|Advance Decline Ratio|Advance Decline Volume Line|Advance Decline Volume Ratio|Arms Index|TRIN|McClellan Oscillator|McClellan Summation Index|New Highs New Lows|High Low Index|High Low Logic Index|Breadth Thrust|Zweig Breadth Thrust|Cumulative Tick|NYSE TICK|NYSE TRIN|Market Thrust|Upside Downside Volume|Up Volume Down Volume Ratio|Percentage of Stocks Above 50 MA|Percentage of Stocks Above 200 MA|Bullish Percent Index|BPI|Coppock Breadth Indicator|Advance Decline Percent|Net New Highs|Net New Lows|52 Week High Low Indicator|Tick Index"},
	{"sentiment", "sentiment_indikatorleri", "Put Call Ratio|Equity Put Call Ratio|Index Put Call Ratio|VIX|VXN|VXD|Fear and Greed Index|AAII Sentiment Survey|Investors Intelligence Sentiment|NAAIM Exposure Index|Commitment of Traders|COT|Smart Money Index|Dumb Money Confidence|Short Interest Ratio|Days to Cover|Margin Debt|Insider Buying Selling Ratio|Options Skew|IV Skew|Volatility Term Structure|Contango Backwardation Indicator|Crypto Fear and Greed Index|Funding Rate|Open Interest|Long Short Ratio|Taker Buy Sell Ratio"},
	{"order_flow", "order_flow_indikatorleri", "Footprint Chart|Volume Footprint|Delta Footprint|Bid Ask Footprint|Cumulative Volume Delta|CVD|Order Flow Delta|Bid Ask Delta|Buy Sell Imbalance|Stacked Imbalance|Absorption Indicator|Iceberg Order Detector|Large Order Detector|Liquidity Heatmap|Market Depth|DOM|Depth of Market|Order Book Imbalance|Order Book Delta|Bookmap Heatmap|Volume Imbalance|Delta Divergence|CVD Divergence|VWAP Delta|Aggressive Buyers Sellers|Time and Sales|Tape Reading Indicator|Volume Cluster|Delta Cluster|POC Cluster|Bid Ask Spread Indicator|Liquidity Sweep Detector|Exhaustion Detector"},
	{"market_profile", "market_profile_indikatorleri", "Market Profile|TPO Profile|Time Price Opportunity|Volume Profile|Session Profile|Fixed Range Volume Profile|Visible Range Volume Profile|Composite Profile|Point of Control|POC|TPO POC|Volume POC|Value Area|Value Area High|VAH|Value Area Low|VAL|Initial Balance|IB|Single Prints|Poor High|Poor Low|Excess High|Excess Low|Naked POC|Virgin POC|High Volume Node|HVN|Low Volume Node|LVN|Developing POC|Developing VAH|Developing VAL|Volume Weighted Average Price|VWAP|Anchored VWAP"},
	{"ichimoku", "ichimoku_indikatorleri", "Ichimoku Kinko Hyo|Tenkan-sen|Kijun-sen|Senkou Span A|Senkou Span B|Chikou Span|Kumo Cloud|Kumo Twist|Kumo Breakout|TK Cross|Kijun Bounce|Cloud Support Resistance|Ichimoku Wave|Ichimoku Time Theory|Ichimoku Price Target"},
	{"gann", "gann_indikatorleri", "Gann Fan|Gann Box|Gann Square|Gann Square of Nine|Gann Angles|Gann Grid|Gann Swing Chart|Gann HiLo Activator|Gann Line|Gann Time Cycle|Gann Price Time Squaring|Gann Wheel"},
	{"fibonacci", "fibonacci_indikatorleri", "Fibonacci Retracement|Fibonacci Extension|Fibonacci Expansion|Fibonacci Projection|Fibonacci Channel|Fibonacci Fan|Fibonacci Arc|Fibonacci Time Zones|Fibonacci Spiral|Fibonacci Circle|Fibonacci Wedge|Fibonacci Speed Resistance Fan|Fibonacci Cluster|Fibonacci Confluence|Auto Fibonacci|Auto Fib Retracement|Auto Fib Extension"},
	{"statistical", "statistical_quant_indikatorleri", "Standard Deviation|Variance|Mean|Median|Mode|Z-Score|Rolling Z-Score|Correlation Coefficient|Beta|Alpha|Sharpe Ratio|Sortino Ratio|Calmar Ratio|Information Ratio|Treynor Ratio|Skewness|Kurtosis|Linear Regression|Linear Regression Slope|Linear Regression Intercept|Linear Regression R-Squared|Standard Error|Standard Error Bands|Percentile Rank|Quantile Bands|Zig Zag|Log Return|Simple Return|Cumulative Return|Drawdown|Maximum Drawdown|Rolling Volatility|Rolling Correlation|Rolling Beta|Hurst Exponent|Half Life of Mean Reversion|Augmented Dickey Fuller Signal|Kalman Filter|Kalman Trend|Kaufman Efficiency Ratio|Entropy Indicator|Shannon Entropy|Fractal Dimension Index|FDI|Hurst Cycle Channel"},
	{"price_transform", "price_transform_indikatorleri", "Average Price|Median Price|Typical Price|Weighted Close Price|Heikin Ashi|Renko|Kagi|Line Break|Point and Figure|Range Bars|Volume Bars|Tick Bars|Dollar Bars|Log Price|Percentage Price|Cumulative Return Price|OHLC4|HLC3|HL2|OC2"},
	{"stop", "stop_loss_trailing_indikatorleri", "Parabolic SAR|ATR Trailing Stop|Chandelier Exit|Supertrend|Volatility Stop|VStop|Kase DevStop|Moving Average Stop|Donchian Stop|Keltner Stop|Bollinger Stop|Swing High Low Stop|Fractal Stop|Gann HiLo Activator|SAR Trailing Stop|N-Bar Stop|Highest High Stop|Lowest Low Stop|Deviation Stop"},
	{"divergence", "divergence_indikatorleri", "RSI Divergence|MACD Divergence|Stochastic Divergence|CCI Divergence|MFI Divergence|OBV Divergence|CVD Divergence|Volume Divergence|Momentum Divergence|Hidden Bullish Divergence|Hidden Bearish Divergence|Regular Bullish Divergence|Regular Bearish Divergence|Class A Divergence|Class B Divergence|Class C Divergence|Exaggerated Divergence"},
	{"smart_money", "smart_money_ict_indikatorleri", "Order Block Indicator|Breaker Block Indicator|Mitigation Block Indicator|Fair Value Gap Indicator|FVG Indicator|Inversion Fair Value Gap|IFVG|Balanced Price Range Indicator|BPR Indicator|Liquidity Sweep Indicator|Liquidity Pool Indicator|Buy Side Liquidity Indicator|Sell Side Liquidity Indicator|Equal Highs Equal Lows Indicator|Premium Discount Zone Indicator|Optimal Trade Entry Indicator|OTE Indicator|Change of Character Indicator|CHoCH Indicator|Break of Structure Indicator|BOS Indicator|Market Structure Shift Indicator|MSS Indicator|Killzone Indicator|Session High Low Indicator|Asian Range Indicator|London Range Indicator|New York Range Indicator|Judas Swing Indicator|Power of Three Indicator|AMD Indicator|Volume Imbalance Indicator|Liquidity Void Detector|Silver Bullet Zone Indicator"},
	{"elliott", "elliott_wave_indikatorleri", "Elliott Wave Oscillator|EWO|Elliott Wave Count|Auto Elliott Wave|WaveTrend Oscillator|WaveTrend|Zig Zag Elliott Wave|Impulse Wave Detector|Corrective Wave Detector|Fibonacci Elliott Wave Tool|Elliott Wave Projection|Elliott Channel"},
	{"wyckoff", "wyckoff_indikatorleri", "Wyckoff Volume|Wyckoff Wave|Wyckoff Effort Result|Wyckoff Spring Detector|Wyckoff Upthrust Detector|Accumulation Distribution Detector|Reaccumulation Detector|Redistribution Detector|Selling Climax Detector|Buying Climax Detector|Sign of Strength Detector|Sign of Weakness Detector|Last Point of Support Detector|Last Point of Supply Detector|Volume Spread Analysis|VSA|No Demand Bar|No Supply Bar|Stopping Volume|Absorption Volume"},
	{"demark", "tom_demark_indikatorleri", "DeMark Sequential|TD Sequential|TD Combo|TD Setup|TD Countdown|TD REI|DeMarker|TD Moving Average|TD Lines|TD Trend Factor|TD Pressure|TD Range Expansion Index|TD Differential|TD Reverse Differential|TD Waldo Patterns"},
	{"crypto_onchain", "crypto_ozel_indikatorler", "Funding Rate|Open Interest|Cumulative Open Interest|Long Short Ratio|Taker Buy Sell Ratio|Liquidation Levels|Liquidation Heatmap|Estimated Leverage Ratio|Exchange Reserve|Exchange Netflow|Miner Reserve|Hash Ribbon|MVRV Ratio|NVT Ratio|SOPR|aSOPR|Realized Price|Realized Cap|Puell Multiple|Stock to Flow|Stablecoin Supply Ratio|SSR|Bitcoin Dominance|Altcoin Season Index|Fear and Greed Index|On Chain Volume|Active Addresses|Network Value to Transactions|UTXO Realized Price Distribution|URPD|Net Unrealized Profit/Loss|NUPL|CME Gap Indicator|Saylor Tracker"},
	{"options", "options_indikatorleri", "Implied Volatility|Historical Volatility|IV Rank|IV Percentile|Put Call Ratio|Open Interest|Options Volume|Gamma Exposure|GEX|Delta Exposure|DEX|Vanna Exposure|Charm Exposure|Max Pain|Skew|Volatility Smile|Volatility Surface|Term Structure|Expected Move|Realized Volatility|Implied Move|Dealer Gamma|Gamma Flip Level|Zero Gamma Level"},
	{"renko_kagi_pnf", "renko_kagi_pnf_indikatorleri", "Renko Chart|ATR Renko|Traditional Renko|Kagi Chart|Line Break Chart|Three Line Break|Point and Figure Chart|P&F Double Top Signal|P&F Double Bottom Signal|P&F Triple Top Signal|P&F Triple Bottom Signal|P&F Bullish Catapult|P&F Bearish Catapult|Renko Trend Indicator|Renko Oscillator|Renko Moving Average|Kagi Trend Indicator"},
	{"heikin_ashi", "heikin_ashi_indikatorleri", "Heikin Ashi Candles|Heikin Ashi Smoothed|Heikin Ashi Oscillator|Heikin Ashi Trend|Heikin Ashi Moving Average|Heikin Ashi RSI|Heikin Ashi MACD"},
	{"session_time", "session_time_indikatorleri", "Session High Low|Daily High Low|Weekly High Low|Monthly High Low|Opening Range|Opening Range Breakout|ORB|Initial Balance|IB|Asian Session Range|London Session Range|New York Session Range|Previous Day High Low|Previous Week High Low|Previous Month High Low|Midnight Open|Daily Open|Weekly Open|Monthly Open|Quarterly Open|Yearly Open|Market Sessions|Killzones|ICT Killzones|Trading Hours Overlay|Asia Sweep London Expansion"},
	{"risk_performance", "risk_performance_indikatorleri", "Sharpe Ratio|Sortino Ratio|Calmar Ratio|Treynor Ratio|Information Ratio|Profit Factor|Expectancy|Win Rate|Risk Reward Ratio|Maximum Drawdown|Average Drawdown|Ulcer Index|Recovery Factor|Kelly Criterion|Value at Risk|VaR|Conditional Value at Risk|CVaR|Beta|Alpha|Tracking Error|Rolling Returns|Equity Curve|Equity Curve Moving Average"},
	{"pattern_recognition", "pattern_recognition_indikatorleri", "Candlestick Pattern Recognition|Doji Detector|Hammer Detector|Engulfing Detector|Morning Star Detector|Evening Star Detector|Harami Detector|Shooting Star Detector|Head and Shoulders Detector|Double Top Detector|Double Bottom Detector|Triangle Pattern Detector|Flag Pattern Detector|Wedge Pattern Detector|Cup and Handle Detector|Harmonic Pattern Scanner|Gartley Scanner|Bat Scanner|Butterfly Scanner|Crab Scanner|Cypher Scanner|ABCD Scanner|Zig Zag Pattern Detector"},
	{"ta_lib", "ta_lib_overlap_studies", "BBANDS|DEMA|EMA|HT_TRENDLINE|KAMA|MA|MAMA|MAVP|MIDPOINT|MIDPRICE|SAR|SAREXT|SMA|T3|TEMA|TRIMA|WMA"},
	{"ta_lib", "ta_lib_momentum_indicators", "ADX|ADXR|APO|AROON|AROONOSC|BOP|CCI|CMO|DX|MACD|MACDEXT|MACDFIX|MFI|MINUS_DI|MINUS_DM|MOM|PLUS_DI|PLUS_DM|PPO|ROC|ROCP|ROCR|ROCR100|RSI|STOCH|STOCHF|STOCHRSI|TRIX|ULTOSC|WILLR"},
	{"ta_lib", "ta_lib_volume_indicators", "AD|ADOSC|OBV"},
	{"ta_lib", "ta_lib_volatility_indicators", "ATR|NATR|TRANGE"},
	{"ta_lib", "ta_lib_price_transform", "AVGPRICE|MEDPRICE|TYPPRICE|WCLPRICE"},
	{"ta_lib", "ta_lib_cycle_indicators", "HT_DCPERIOD|HT_DCPHASE|HT_PHASOR|HT_SINE|HT_TRENDMODE"},
	{"ta_lib", "ta_lib_statistic_functions", "BETA|CORREL|LINEARREG|LINEARREG_ANGLE|LINEARREG_INTERCEPT|LINEARREG_SLOPE|STDDEV|TSF|VAR"},
	{"other", "diger_yaygin_indikatorler", "TRIX|Trix Indicator|Elder Impulse System|Elder Triple Screen|Rainbow Moving Average|Rainbow Oscillator|Zig Zag|Percent Rank|Relative Strength Comparative|Relative Strength Ratio|Mansfield Relative Strength|Mansfield RS|Relative Rotation Graph|RRG|JdK RS-Ratio|JdK RS-Momentum|Darvas Box|Fractal Chaos Oscillator|Fractal Chaos Bands|Polarized Fractal Efficiency|Projection Oscillator|Projection Bands|Random Walk Index|RWI|Swing Index|Accumulation Swing Index|ASI|Commodity Selection Index|CSI|Herrick Payoff Index|HPI|Prime Number Bands|Prime Number Oscillator|Rainbow Charts|Trade Volume Index|TVI|Twiggs Momentum|Twiggs Volatility|Twiggs Money Flow|Mass Index|Range Action Verification Index|RAVI|Moving Average Deviation|Price Distance from MA|Candle Body Size Indicator|Wick Ratio Indicator|ATR Percent|Range Percent|Gap Indicator|News Volatility Indicator"},
}
