package quant

type ModuleSupport struct {
	Name     string `json:"name"`
	Tier     string `json:"tier"`
	Package  string `json:"package"`
	Function string `json:"function"`
}

func SupportedModules() []ModuleSupport {
	return []ModuleSupport{
		{Name: "Scheduling", Tier: "Core", Package: "internal/quant/core", Function: "GenerateSchedule"},
		{Name: "Statistics", Tier: "Basic", Package: "internal/quant/core", Function: "Mean/Variance/StdDev/Covariance/Correlation/Quantile"},
		{Name: "Numerical Solver", Tier: "Basic", Package: "internal/quant/solver", Function: "Bisection/Newton/Secant"},
		{Name: "Calculate Bond Yield to Maturity", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "YieldToMaturity"},
		{Name: "Calculate Macaulay Duration", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "MacaulayDuration"},
		{Name: "Calculate Modified Duration", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "ModifiedDuration"},
		{Name: "Calculate Bond Convexity", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "Convexity"},
		{Name: "Calculate Convexity Adjustment", Tier: "Standard", Package: "internal/quant/rates", Function: "ConvexityAdjustment"},
		{Name: "Calculate Discount Factor from Rate", Tier: "Standard", Package: "internal/quant/rates", Function: "DiscountFactorFromRate"},
		{Name: "Calculate Zero Rate from Discount Factor", Tier: "Standard", Package: "internal/quant/rates", Function: "ZeroRateFromDiscountFactor"},
		{Name: "Calculate Forward Rate from Discount Factors", Tier: "Standard", Package: "internal/quant/rates", Function: "ForwardRateFromDiscountFactors"},
		{Name: "Calculate Par Swap Rate", Tier: "Standard", Package: "internal/quant/rates", Function: "ParSwapRate"},
		{Name: "Calculate PV01 (DV01)", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "PV01"},
		{Name: "Calculate Internal Rate of Return (IRR)", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "InternalRateOfReturn"},
		{Name: "Calculate Extended IRR (XIRR)", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "XIRR"},
		{Name: "Calculate Black-Scholes Implied Volatility", Tier: "Standard", Package: "internal/quant/options", Function: "BlackScholesImpliedVolatility"},
		{Name: "Calculate Black76 Implied Volatility", Tier: "Standard", Package: "internal/quant/options", Function: "Black76ImpliedVolatility"},
		{Name: "Calculate G-Spread", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "GSpread"},
		{Name: "Calculate I-Spread", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "ISpread"},
		{Name: "Calculate Z-Spread", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "ZSpread"},
		{Name: "Calculate Basis", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "Basis"},
		{Name: "Calculate Cost of Carry", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "CostOfCarryRate"},
		{Name: "Calculate Implied Repo Rate", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "ImpliedRepoRate"},
		{Name: "Convert Between Forward and Futures Rates", Tier: "Standard", Package: "internal/quant/rates", Function: "ForwardToFuturesRate/FuturesToForwardRate"},
		{Name: "Calculate Asset Swap Spread", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "AssetSwapSpread"},
		{Name: "Calculate Option-Adjusted Spread (OAS)", Tier: "Standard", Package: "internal/quant/fixedincome", Function: "OptionAdjustedSpread"},
		{Name: "Calibrate Vasicek Short Rate Model", Tier: "Standard", Package: "internal/quant/rates", Function: "CalibrateVasicek"},
		{Name: "Bootstrap Discount Curve from Market Instruments", Tier: "Standard", Package: "internal/quant/rates", Function: "BootstrapDiscountCurve"},
		{Name: "Black-Scholes Option Price", Tier: "Pro", Package: "internal/quant/options", Function: "BlackScholesPrice"},
		{Name: "Black-Scholes Greeks (Basic)", Tier: "Pro", Package: "internal/quant/options", Function: "BlackScholesGreeks"},
		{Name: "Black-Scholes Full Greeks Suite", Tier: "Pro", Package: "internal/quant/options", Function: "BlackScholesFullGreeks"},
		{Name: "Black-Scholes Digital Call (Cash-or-Nothing)", Tier: "Pro", Package: "internal/quant/options", Function: "DigitalCashOrNothing"},
		{Name: "Black-Scholes Digital Put (Cash-or-Nothing)", Tier: "Pro", Package: "internal/quant/options", Function: "DigitalCashOrNothing"},
		{Name: "Black-Scholes Asset-or-Nothing Call", Tier: "Pro", Package: "internal/quant/options", Function: "AssetOrNothing"},
		{Name: "Black-Scholes Asset-or-Nothing Put", Tier: "Pro", Package: "internal/quant/options", Function: "AssetOrNothing"},
		{Name: "Black76 Option Price", Tier: "Pro", Package: "internal/quant/options", Function: "Black76Price"},
		{Name: "Black76 Greeks (Basic)", Tier: "Pro", Package: "internal/quant/options", Function: "Black76Greeks"},
		{Name: "Black76 Full Greeks Suite", Tier: "Pro", Package: "internal/quant/options", Function: "Black76FullGreeks"},
		{Name: "Black76 Caplet Price", Tier: "Pro", Package: "internal/quant/options", Function: "Black76CapletPrice"},
		{Name: "Black76 Floorlet Price", Tier: "Pro", Package: "internal/quant/options", Function: "Black76FloorletPrice"},
		{Name: "Black76 Swaption Price", Tier: "Pro", Package: "internal/quant/options", Function: "Black76SwaptionPrice"},
		{Name: "Bachelier Option Price", Tier: "Pro", Package: "internal/quant/options", Function: "BachelierPrice"},
		{Name: "Bachelier Greeks (Basic)", Tier: "Pro", Package: "internal/quant/options", Function: "BachelierGreeks"},
		{Name: "Bachelier Full Greeks Suite", Tier: "Pro", Package: "internal/quant/options", Function: "BachelierFullGreeks"},
		{Name: "Bachelier Implied Volatility", Tier: "Pro", Package: "internal/quant/options", Function: "BachelierImpliedVolatility"},
		{Name: "Volatility Conversion (Lognormal ↔ Normal)", Tier: "Pro", Package: "internal/quant/options", Function: "VolatilityLognormalToNormal/VolatilityNormalToLognormal"},
		{Name: "Shifted Lognormal Option Price", Tier: "Pro", Package: "internal/quant/options", Function: "ShiftedLognormalPrice"},
		{Name: "Kirk Spread Option Price", Tier: "Pro", Package: "internal/quant/options", Function: "KirkSpreadOption"},
		{Name: "Kirk Spread Option Greeks", Tier: "Pro", Package: "internal/quant/options", Function: "KirkSpreadOptionGreeks"},
		{Name: "Margrabe Exchange Option Price", Tier: "Pro", Package: "internal/quant/options", Function: "MargrabeExchangeOption"},
		{Name: "Basket Option Price (Levy Approximation)", Tier: "Pro", Package: "internal/quant/options", Function: "BasketOptionLevy"},
		{Name: "Binomial Tree European Option", Tier: "Pro", Package: "internal/quant/options", Function: "BinomialEuropean"},
		{Name: "Binomial Tree American Option", Tier: "Pro", Package: "internal/quant/options", Function: "BinomialAmerican"},
		{Name: "Binomial Tree Bermudan Option", Tier: "Pro", Package: "internal/quant/options", Function: "BinomialBermudan"},
		{Name: "Binomial Tree Barrier Option", Tier: "Pro", Package: "internal/quant/options", Function: "BinomialBarrier"},
		{Name: "Bond Fixed Cashflows", Tier: "Pro", Package: "internal/quant/instruments", Function: "BondFixedCashflows"},
		{Name: "Bond Fixed Price", Tier: "Pro", Package: "internal/quant/instruments", Function: "BondFixedPrice"},
		{Name: "Bond Fixed Yield", Tier: "Pro", Package: "internal/quant/instruments", Function: "BondFixedYield"},
		{Name: "Bond Fixed Analytics", Tier: "Pro", Package: "internal/quant/instruments", Function: "BondFixedAnalytics"},
		{Name: "Zero Coupon Price", Tier: "Pro", Package: "internal/quant/instruments", Function: "ZeroCouponPrice"},
		{Name: "Inflation Linked Bond", Tier: "Pro", Package: "internal/quant/instruments", Function: "InflationLinkedBondPrice"},
		{Name: "Irs Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "IRSValue"},
		{Name: "Irs Par Rate", Tier: "Pro", Package: "internal/quant/instruments", Function: "IRSParRate"},
		{Name: "Irs Dv01", Tier: "Pro", Package: "internal/quant/instruments", Function: "IRSDV01"},
		{Name: "Fra Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "FRAValue"},
		{Name: "Fra Break Even", Tier: "Pro", Package: "internal/quant/instruments", Function: "FRABreakEven"},
		{Name: "Deposit Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "DepositValue"},
		{Name: "Tbill Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "TBillValue"},
		{Name: "Repo Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "RepoValue"},
		{Name: "Ois Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "OISValue"},
		{Name: "Ois Build Curve", Tier: "Pro", Package: "internal/quant/instruments", Function: "OISBuildCurve"},
		{Name: "Variance Swap", Tier: "Pro", Package: "internal/quant/instruments", Function: "VarianceSwapValue"},
		{Name: "Volatility Swap", Tier: "Pro", Package: "internal/quant/instruments", Function: "VolatilitySwapValue"},
		{Name: "Commodity Future", Tier: "Pro", Package: "internal/quant/instruments", Function: "CommodityFuture"},
		{Name: "Fx Forward", Tier: "Pro", Package: "internal/quant/instruments", Function: "FXForward"},
		{Name: "Fx Garman Kohlhagen", Tier: "Pro", Package: "internal/quant/instruments", Function: "FXGarmanKohlhagen"},
		{Name: "Cds Value", Tier: "Pro", Package: "internal/quant/instruments", Function: "CDSValue"},
		{Name: "Cds Hazard Rate", Tier: "Pro", Package: "internal/quant/instruments", Function: "CDSHazardRate"},
		{Name: "Survival Probability", Tier: "Pro", Package: "internal/quant/instruments", Function: "SurvivalProbability"},
		{Name: "Stir Future", Tier: "Pro", Package: "internal/quant/instruments", Function: "STIRFuturePrice/STIRFutureRate"},
		{Name: "Bond Future Ctd", Tier: "Pro", Package: "internal/quant/instruments", Function: "BondFutureCTD"},
		{Name: "Flat Volatility Surface", Tier: "Pro", Package: "internal/quant/volatility", Function: "FlatSurface"},
		{Name: "Term Structure Volatility", Tier: "Pro", Package: "internal/quant/volatility", Function: "TermStructure"},
		{Name: "Volatility Surface Grid", Tier: "Pro", Package: "internal/quant/volatility", Function: "GridSurface"},
		{Name: "Volatility Smile", Tier: "Pro", Package: "internal/quant/volatility", Function: "SABRSmile"},
		{Name: "Total Variance from Surface", Tier: "Pro", Package: "internal/quant/volatility", Function: "TotalVariance"},
		{Name: "Build Surface From Points", Tier: "Pro", Package: "internal/quant/volatility", Function: "BuildSurfaceFromPoints"},
		{Name: "SABR Implied Volatility", Tier: "Pro", Package: "internal/quant/volatility", Function: "SABRImpliedVolatility"},
		{Name: "SABR Normal Volatility", Tier: "Pro", Package: "internal/quant/volatility", Function: "SABRNormalVolatility"},
		{Name: "SABR Volatility Smile", Tier: "Pro", Package: "internal/quant/volatility", Function: "SABRSmile"},
		{Name: "Calibrate SABR Model", Tier: "Pro", Package: "internal/quant/volatility", Function: "CalibrateSABR"},
		{Name: "SABR Probability Density", Tier: "Pro", Package: "internal/quant/volatility", Function: "SABRProbabilityDensity"},
		{Name: "SABR Smile Dynamics", Tier: "Pro", Package: "internal/quant/volatility", Function: "SABRSmileDynamics"},
		{Name: "Constant Local Volatility", Tier: "Pro", Package: "internal/quant/volatility", Function: "ConstantLocalVolatility"},
		{Name: "Implied to Local Volatility Conversion", Tier: "Pro", Package: "internal/quant/volatility", Function: "ImpliedToLocalVolatility"},
		{Name: "Minimum Variance Portfolio", Tier: "Pro", Package: "internal/quant/portfolio", Function: "MinimumVariancePortfolio"},
		{Name: "Maximum Sharpe Ratio Portfolio", Tier: "Pro", Package: "internal/quant/portfolio", Function: "MaximumSharpeRatioPortfolio"},
		{Name: "Target Return Portfolio", Tier: "Pro", Package: "internal/quant/portfolio", Function: "TargetReturnPortfolio"},
		{Name: "Efficient Frontier", Tier: "Pro", Package: "internal/quant/portfolio", Function: "EfficientFrontier"},
		{Name: "Black-Litterman Equilibrium Returns", Tier: "Pro", Package: "internal/quant/portfolio", Function: "BlackLittermanEquilibriumReturns"},
		{Name: "Black-Litterman Posterior Returns & Weights", Tier: "Pro", Package: "internal/quant/portfolio", Function: "BlackLittermanPosteriorReturns"},
		{Name: "Risk Parity Portfolio", Tier: "Pro", Package: "internal/quant/portfolio", Function: "RiskParityPortfolio"},
		{Name: "Comprehensive Portfolio Risk Analysis", Tier: "Pro", Package: "internal/quant/portfolio", Function: "ComprehensiveRiskAnalysis"},
		{Name: "Portfolio Value at Risk (VaR)", Tier: "Pro", Package: "internal/quant/portfolio", Function: "HistoricalVaR/ParametricVaR"},
		{Name: "Portfolio Conditional Value at Risk (CVaR)", Tier: "Pro", Package: "internal/quant/portfolio", Function: "HistoricalCVaR"},
		{Name: "Risk Contribution Analysis", Tier: "Pro", Package: "internal/quant/portfolio", Function: "RiskContribution"},
		{Name: "Portfolio Risk-Adjusted Performance Ratios", Tier: "Pro", Package: "internal/quant/portfolio", Function: "PerformanceRatios"},
		{Name: "Incremental Value at Risk", Tier: "Pro", Package: "internal/quant/portfolio", Function: "IncrementalVaR"},
		{Name: "Inverse Volatility Weights", Tier: "Pro", Package: "internal/quant/portfolio", Function: "InverseVolatilityWeights"},
		{Name: "Comprehensive Portfolio Risk Assessment", Tier: "Pro", Package: "internal/quant/portfolio", Function: "ComprehensiveRiskAnalysis"},
	}
}
