package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type rawSpec struct {
	Name     string
	Category string
	Group    string
}

type generatedSpec struct {
	Name       string
	Category   string
	Group      string
	Direction  string
	Template   string
	Confidence float64
	Evidence   string
}

var explicitTemplateOverrides = map[string]string{
	"absorption":                    "volume",
	"amd pattern":                   "amd",
	"back up to the creek":          "lps",
	"back up to the ice":            "lpsy",
	"blow off top":                  "buying_climax",
	"bos":                           "bos",
	"break and retest":              "break_retest",
	"buying exhaustion":             "buying_climax",
	"cause and effect":              "range",
	"cheat area":                    "compression",
	"composite operator":            "wyckoff_composite",
	"creek":                         "sos",
	"dead cat bounce":               "dead_cat_bounce",
	"demand zone rejection":         "spring",
	"ascending scallop":             "rounding_bottom",
	"discount zone":                 "discount_zone",
	"descending scallop":            "rounding_top",
	"equilibrium seviyesi":          "equilibrium_zone",
	"external liquidity":            "liquidity_sweep",
	"fakey pattern":                 "fakey",
	"failed move":                   "false_breakout",
	"fall through the ice":          "sow",
	"high resistance liquidity run": "liquidity_sweep",
	"hrlr":                          "liquidity_sweep",
	"ice":                           "sow",
	"idm":                           "liquidity_sweep",
	"inducement":                    "liquidity_sweep",
	"inside bar fakey":              "fakey",
	"inside bar range":              "mother_bar",
	"internal liquidity":            "liquidity_sweep",
	"inverted ascending scallop":    "rounding_top",
	"inverted descending scallop":   "rounding_bottom",
	"inverted roof pattern":         "rounding_bottom",
	"jump across the creek":         "sos",
	"low resistance liquidity run":  "liquidity_sweep",
	"lps":                           "lps",
	"lrlr":                          "liquidity_sweep",
	"mean reversion setup":          "mean_reversion",
	"mother bar":                    "mother_bar",
	"optimal trade entry":           "fibonacci",
	"ote":                           "fibonacci",
	"over and under pattern":        "quasimodo",
	"overthrow":                     "upthrust",
	"pocket pivot":                  "pocket_pivot",
	"power of three":                "amd",
	"preliminary supply":            "buying_climax",
	"preliminary support":           "selling_climax",
	"premium zone":                  "premium_zone",
	"ps":                            "selling_climax",
	"psy":                           "buying_climax",
	"pullback":                      "pullback",
	"quasimodo pattern":             "quasimodo",
	"roof pattern":                  "rounding_top",
	"rounded reversal":              "rounded_reversal",
	"secondary test":                "secondary_test",
	"selling exhaustion":            "selling_climax",
	"shakeout":                      "spring",
	"silver bullet setup":           "fvg",
	"st":                            "secondary_test",
	"stair step pattern":            "stair_step",
	"supply zone rejection":         "upthrust",
	"support resistance flip":       "break_retest",
	"three falling peaks":           "trend_down",
	"three rising valleys":          "trend_up",
	"throwback":                     "break_retest",
	"throwover":                     "upthrust",
	"trend exhaustion":              "trend_exhaustion",
	"trendline break":               "trendline_break",
	"trendline retest":              "break_retest",
	"undercut":                      "spring",
	"undercut and rally":            "spring",
	"wedge":                         "wedge",
	"wedge continuation":            "wedge",
}

func main() {
	var root any
	if err := json.Unmarshal([]byte(catalogJSON), &root); err != nil {
		log.Fatal(err)
	}
	raw := collect(root)
	seen := map[string]generatedSpec{}
	for _, item := range raw {
		key := strings.ToLower(strings.TrimSpace(item.Name))
		if key == "" {
			continue
		}
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = infer(item)
	}
	specs := make([]generatedSpec, 0, len(seen))
	for _, spec := range seen {
		specs = append(specs, spec)
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })

	outDir := filepath.Join("internal", "ta", "patterns", "generated")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		log.Fatal(err)
	}
	specFile := filepath.Join(outDir, "spec.go")
	specData := `// Code generated by tools/pattern_catalog_gen; DO NOT EDIT.
package generated

type Spec struct {
	Name       string
	Category   string
	Group      string
	Direction  string
	Template   string
	Confidence float64
	Evidence   string
}

var Specs []Spec
`
	if err := os.WriteFile(specFile, []byte(specData), 0o644); err != nil {
		log.Fatal(err)
	}
	for _, spec := range specs {
		path := filepath.Join(outDir, "pattern_"+slug(spec.Name)+".go")
		data := fmt.Sprintf(`// Code generated by tools/pattern_catalog_gen; DO NOT EDIT.
package generated

func init() {
	Specs = append(Specs, Spec{
		Name:       %q,
		Category:   %q,
		Group:      %q,
		Direction:  %q,
		Template:   %q,
		Confidence: %.2f,
		Evidence:   %q,
	})
}
`, spec.Name, spec.Category, spec.Group, spec.Direction, spec.Template, spec.Confidence, spec.Evidence)
		if err := os.WriteFile(path, []byte(data), 0o644); err != nil {
			log.Fatal(err)
		}
	}
	fmt.Printf("generated %d pattern files\n", len(specs))
}

func collect(root any) []rawSpec {
	var specs []rawSpec
	var walk func(any, []string)
	walk = func(value any, path []string) {
		switch node := value.(type) {
		case map[string]any:
			keys := make([]string, 0, len(node))
			for key := range node {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			for _, key := range keys {
				walk(node[key], append(path, key))
			}
		case []any:
			for _, item := range node {
				if text, ok := item.(string); ok {
					specs = append(specs, rawSpec{Name: text, Category: categoryFromPath(path), Group: groupFromPath(path)})
					continue
				}
				walk(item, path)
			}
		}
	}
	walk(root, nil)
	return specs
}

func categoryFromPath(path []string) string {
	for _, part := range path {
		if part != "kategoriler" {
			return part
		}
	}
	return "diger"
}

func groupFromPath(path []string) string {
	for _, part := range path {
		if part != "kategoriler" && part != categoryFromPath(path) {
			return part
		}
	}
	return categoryFromPath(path)
}

func infer(raw rawSpec) generatedSpec {
	category := canonicalCategory(raw.Category)
	name := raw.Name
	normalized := normalize(name)
	direction := inferDirection(normalized)
	template := inferTemplate(category, normalized)
	direction = refineDirection(normalized, template, direction)
	confidence := 0.62
	if category == "candlestick" {
		confidence = 0.66
	}
	if category == "classic_chart" || category == "harmonic" {
		confidence = 0.64
	}
	if category == "indicator" || category == "market_profile" || category == "point_and_figure" {
		confidence = 0.58
	}
	return generatedSpec{
		Name:       name,
		Category:   category,
		Group:      raw.Group,
		Direction:  direction,
		Template:   template,
		Confidence: confidence,
		Evidence:   evidenceFor(template),
	}
}

func canonicalCategory(value string) string {
	switch value {
	case "japon_mum_candlestick_formasyonlari":
		return "candlestick"
	case "klasik_grafik_formasyonlari":
		return "classic_chart"
	case "harmonik_formasyonlar":
		return "harmonic"
	case "price_action_formasyonlari":
		return "price_action"
	case "elliott_wave_formasyonlari":
		return "elliott_wave"
	case "wyckoff_formasyonlari":
		return "wyckoff"
	case "gap_bosluk_formasyonlari":
		return "gap"
	case "volume_hacim_formasyonlari":
		return "volume"
	case "trend_kanal_formasyonlari":
		return "trend_channel"
	case "indicator_tabanli_formasyonlar":
		return "indicator"
	case "point_and_figure_formasyonlari":
		return "point_and_figure"
	case "market_profile_auction_formasyonlari":
		return "market_profile"
	case "fibonacci_formasyonlari":
		return "fibonacci"
	case "diger_bilinen_formasyonlar":
		return "other"
	default:
		return "other"
	}
}

func inferDirection(name string) string {
	switch {
	case hasAny(name, "sell signal", "no demand", "buying climax", "buying exhaustion", "bull trap", "lpsy", "buy side liquidity"):
		return "bearish"
	case hasAny(name, "buy signal", "no supply", "selling climax", "selling exhaustion", "stopping volume", "bear trap", "sell side liquidity"):
		return "bullish"
	case hasAny(name, "bullish", "support", "demand", "buy ", "buying", "uptrend", "upside", "accumulation", "rally", "strength", "golden", "positive", "higher high", "higher low", "discount", "spring", "lps", "breakout", "advance") || hasWord(name, "bottom"):
		return "bullish"
	}
	if hasAny(name, "bearish", "resistance", "supply", "sell ", "selling", "downtrend", "downside", "distribution", "reaction", "weakness", "death", "negative", "lower high", "lower low", "premium", "upthrust", "lpsy", "breakdown", "decline") || hasWord(name, "top") {
		return "bearish"
	}
	return "neutral"
}

func refineDirection(name, template, direction string) string {
	if refined := directionForName(name); refined != "" {
		return refined
	}
	if refined := directionForTemplate(template); refined != "" {
		return refined
	}
	if refined := directionForCandlestick(name); refined != "" {
		return refined
	}
	return direction
}

func directionForName(name string) string {
	switch name {
	case "ps":
		return "bullish"
	case "psy":
		return "bearish"
	case "bc":
		return "bearish"
	case "sc":
		return "bullish"
	case "ar":
		return "bullish"
	case "utad":
		return "bearish"
	case "sos":
		return "bullish"
	case "sow":
		return "bearish"
	}
	switch {
	case hasAny(name, "sell signal", "no demand", "buying climax", "buying exhaustion", "bull trap", "lpsy", "buy side liquidity"):
		return "bearish"
	case hasAny(name, "buy signal", "no supply", "selling climax", "selling exhaustion", "stopping volume", "bear trap", "sell side liquidity"):
		return "bullish"
	default:
		return ""
	}
}

func directionForTemplate(template string) string {
	switch template {
	case "double_top", "triple_top", "head_shoulders", "complex_head_shoulders", "triangle_descending", "flag_bear", "pennant_bear", "wedge_rising", "inverse_cup_handle", "rounding_top", "diamond_top", "wyckoff_distribution", "upthrust", "sow", "lpsy", "buying_climax", "automatic_reaction", "bos_bear", "choch_bear", "equal_highs", "measured_move_down", "bump_run_top", "island_top", "pipe_top", "v_top", "gap_down", "false_breakout", "breakdown", "trend_down":
		return "bearish"
	case "double_bottom", "triple_bottom", "inverse_head_shoulders", "complex_inverse_head_shoulders", "triangle_ascending", "flag_bull", "pennant_bull", "wedge_falling", "cup_handle", "rounding_bottom", "diamond_bottom", "wyckoff_accumulation", "spring", "sos", "lps", "selling_climax", "automatic_rally", "bos_bull", "choch_bull", "equal_lows", "measured_move_up", "bump_run_bottom", "island_bottom", "pipe_bottom", "v_bottom", "bear_trap", "gap_up", "breakout", "trend_up":
		return "bullish"
	default:
		return ""
	}
}

// candlestickDirectionOverrides pins the direction of specific named candlestick
// patterns whose classic definition is unambiguous but whose name either isn't caught
// by the substring heuristics below, or is a substring composed with another word that
// breaks a heuristic match (e.g. "evening doji star" does not contain "evening star").
// Checked before the heuristics so it always wins for these exact names.
var candlestickDirectionOverrides = map[string]string{
	"three inside down":       "bearish",
	"three outside down":      "bearish",
	"concealing baby swallow": "bullish",
	"thrusting line":          "bearish",
	"matching high":           "bearish",
	"in neck line":            "bearish",
	"on neck line":            "bearish",
	"evening doji star":       "bearish",
	"morning doji star":       "bullish",
	"upside tasuki gap":       "bullish",
	"downside tasuki gap":     "bearish",
	"high price gapping play": "bullish",
	"low price gapping play":  "bearish",
	"breaking high signal":    "bullish",
	"breaking low signal":     "bearish",
	"rising mat hold":         "bullish",
	"falling mat hold":        "bearish",
}

func directionForCandlestick(name string) string {
	if direction, ok := candlestickDirectionOverrides[name]; ok {
		return direction
	}
	switch {
	case strings.Contains(name, "bearish"):
		return "bearish"
	case strings.Contains(name, "bullish"):
		return "bullish"
	case hasAny(name, "hanging man", "shooting star", "gravestone doji", "evening star", "dark cloud", "three black", "three crows", "two crows", "advance block", "deliberation", "stalled", "descending hawk", "falling three", "falling window", "bearish abandoned baby", "bearish breakaway", "bearish counterattack", "bearish doji star", "bearish engulfing", "bearish harami", "bearish kicking", "bearish marubozu", "bearish meeting lines", "bearish separating", "bearish tri star", "downside gap", "upside gap two crows", "tower top", "tweezer top", "long upper shadow"):
		return "bearish"
	case hasAny(name, "hammer", "inverted hammer", "dragonfly doji", "morning star", "piercing line", "three white", "three advancing", "rising three", "rising window", "bullish abandoned baby", "bullish breakaway", "bullish counterattack", "bullish doji star", "bullish engulfing", "bullish harami", "bullish kicking", "bullish marubozu", "bullish meeting lines", "bullish separating", "bullish tri star", "homing pigeon", "ladder bottom", "matching low", "stick sandwich", "takuri", "three inside up", "three outside up", "three stars in the south", "unique three river", "tweezer bottom", "upside gap", "long lower shadow"):
		return "bullish"
	case hasAny(name, "spinning top", "doji", "high wave", "rickshaw", "marubozu", "belt hold", "counterattack", "meeting lines", "separating lines", "harami", "engulfing", "window", "gap", "short body", "long body", "short line", "long line"):
		return "neutral"
	default:
		return ""
	}
}

func inferTemplate(category, name string) string {
	if category == "candlestick" {
		return "candlestick"
	}
	if category == "indicator" {
		return "indicator"
	}
	if category == "fibonacci" {
		return "fibonacci"
	}
	if category == "point_and_figure" {
		return "point_figure"
	}
	if category == "market_profile" {
		return "market_profile"
	}
	if category == "volume" {
		return "volume"
	}
	if template, ok := explicitTemplateOverrides[name]; ok {
		return template
	}
	if hasAny(name, "double top", "adam and eve top", "eve and adam top", "adam and adam double top") {
		if hasAny(name, "adam", "eve") {
			return "adam_eve_top"
		}
		return "double_top"
	}
	if hasAny(name, "double bottom", "adam and eve bottom", "eve and adam bottom", "eve and eve double bottom") {
		if hasAny(name, "adam", "eve") {
			return "adam_eve_bottom"
		}
		return "double_bottom"
	}
	if strings.Contains(name, "triple top") {
		return "triple_top"
	}
	if strings.Contains(name, "triple bottom") {
		return "triple_bottom"
	}
	if strings.Contains(name, "complex inverse head and shoulders") {
		return "complex_inverse_head_shoulders"
	}
	if strings.Contains(name, "complex head and shoulders") {
		return "complex_head_shoulders"
	}
	if strings.Contains(name, "inverse head and shoulders") {
		return "inverse_head_shoulders"
	}
	if strings.Contains(name, "head and shoulders") {
		return "head_shoulders"
	}
	if strings.Contains(name, "ascending triangle") {
		return "triangle_ascending"
	}
	if strings.Contains(name, "descending triangle") {
		return "triangle_descending"
	}
	if strings.Contains(name, "triangle") || strings.Contains(name, "coil") {
		return "triangle_symmetrical"
	}
	if hasAny(name, "bullish flag", "high tight flag") {
		return "flag_bull"
	}
	if strings.Contains(name, "bearish flag") {
		return "flag_bear"
	}
	if strings.Contains(name, "bullish pennant") {
		return "pennant_bull"
	}
	if strings.Contains(name, "bearish pennant") {
		return "pennant_bear"
	}
	if strings.Contains(name, "pennant") {
		return "triangle_symmetrical"
	}
	if hasAny(name, "rising wedge", "ascending broadening wedge") {
		return "wedge_rising"
	}
	if hasAny(name, "falling wedge", "descending broadening wedge") {
		return "wedge_falling"
	}
	if hasAny(name, "inverted cup", "inverse cup") {
		return "inverse_cup_handle"
	}
	if hasAny(name, "cup and handle", "saucer with handle") {
		return "cup_handle"
	}
	if hasAny(name, "rounding top", "rounded reversal", "saucer") && strings.Contains(name, "top") {
		return "rounding_top"
	}
	if hasAny(name, "rounding bottom", "saucer bottom", "fry pan bottom") {
		return "rounding_bottom"
	}
	if hasAny(name, "rectangle", "trading range", "consolidation range", "box", "darvas", "base", "flat base", "accumulation range", "distribution range") {
		return "range"
	}
	if strings.Contains(name, "ascending channel") {
		return "channel_ascending"
	}
	if strings.Contains(name, "descending channel") {
		return "channel_descending"
	}
	if hasAny(name, "channel", "pitchfork", "median line", "fan lines", "speed lines") {
		return "channel_horizontal"
	}
	if hasAny(name, "broadening", "megaphone") {
		return "broadening"
	}
	if strings.Contains(name, "diamond top") {
		return "diamond_top"
	}
	if strings.Contains(name, "diamond bottom") {
		return "diamond_bottom"
	}
	if strings.Contains(name, "diamond") {
		return "broadening"
	}
	if hasAny(name, "ab cd", "abcd", "ab=cd") {
		return "abcd"
	}
	if strings.Contains(name, "gartley") {
		return "harmonic_gartley"
	}
	if strings.Contains(name, "butterfly") {
		return "harmonic_butterfly"
	}
	if strings.Contains(name, "deep crab") {
		return "harmonic_deep_crab"
	}
	if strings.Contains(name, "crab") {
		return "harmonic_crab"
	}
	if strings.Contains(name, "shark") {
		return "harmonic_shark"
	}
	if strings.Contains(name, "cypher") {
		return "harmonic_cypher"
	}
	if strings.Contains(name, "bat") {
		return "harmonic_bat"
	}
	if hasAny(name, "white swan", "black swan", "nen star", "leonardo", "sea pony", "one2one", "121", "anti ", "navarro", "total 1 2 3") {
		return "harmonic_generic"
	}
	if strings.Contains(name, "three drives") {
		return "three_drives"
	}
	if strings.Contains(name, "5 0") {
		return "five_zero"
	}
	if hasAny(name, "impulse", "motive", "extended first", "extended third", "extended fifth", "truncated fifth") {
		return "elliott_impulse"
	}
	if hasAny(name, "zigzag", "wxy", "double three", "triple three", "irregular correction", "corrective", "correction") && !strings.Contains(name, "flat") && !strings.Contains(name, "triangle") {
		return "elliott_abc"
	}
	if strings.Contains(name, "expanded flat") {
		return "elliott_expanded_flat"
	}
	if strings.Contains(name, "running flat") {
		return "elliott_running_flat"
	}
	if strings.Contains(name, "flat") {
		return "elliott_flat"
	}
	if strings.Contains(name, "diagonal") {
		return "elliott_diagonal"
	}
	if hasAny(name, "accumulation", "re accumulation") {
		return "wyckoff_accumulation"
	}
	if hasAny(name, "distribution", "re distribution") {
		return "wyckoff_distribution"
	}
	if strings.Contains(name, "spring") {
		return "spring"
	}
	if hasAny(name, "upthrust", "utad") {
		return "upthrust"
	}
	if strings.Contains(name, "sign of strength") || isToken(name, "sos") {
		return "sos"
	}
	if strings.Contains(name, "sign of weakness") || isToken(name, "sow") {
		return "sow"
	}
	if strings.Contains(name, "last point of support") || isToken(name, "lps") {
		return "lps"
	}
	if hasAny(name, "last point of supply", "lpsy") {
		return "lpsy"
	}
	if strings.Contains(name, "buying climax") || strings.Contains(name, "climax top") || isToken(name, "bc") {
		return "buying_climax"
	}
	if strings.Contains(name, "selling climax") || strings.Contains(name, "climax bottom") || isToken(name, "sc") {
		return "selling_climax"
	}
	if strings.Contains(name, "automatic rally") || name == "ar" {
		return "automatic_rally"
	}
	if strings.Contains(name, "automatic reaction") {
		return "automatic_reaction"
	}
	if strings.Contains(name, "break of structure") || isToken(name, "bos") {
		if inferDirection(name) == "bearish" {
			return "bos_bear"
		}
		return "bos_bull"
	}
	if hasAny(name, "change of character", "choch", "market structure shift", "mss") {
		if inferDirection(name) == "bearish" {
			return "choch_bear"
		}
		return "choch_bull"
	}
	if hasAny(name, "liquidity sweep", "liquidity grab", "stop hunt", "swing failure", "sfp", "turtle soup", "judas") {
		return "liquidity_sweep"
	}
	if hasAny(name, "fair value gap", "fvg", "imbalance", "liquidity void", "balanced price range", "bpr") {
		return "fvg"
	}
	if strings.Contains(name, "order block") {
		if inferDirection(name) == "bearish" {
			return "order_block_bear"
		}
		return "order_block_bull"
	}
	if hasAny(name, "breaker", "rejection block", "propulsion block") {
		return "breaker"
	}
	if strings.Contains(name, "mitigation") {
		return "mitigation"
	}
	if hasAny(name, "equal highs", "buy side liquidity") {
		return "equal_highs"
	}
	if hasAny(name, "equal lows", "sell side liquidity") {
		return "equal_lows"
	}
	if strings.Contains(name, "measured move up") {
		return "measured_move_up"
	}
	if strings.Contains(name, "measured move down") {
		return "measured_move_down"
	}
	if strings.Contains(name, "measured move") {
		return "abcd"
	}
	if strings.Contains(name, "bump and run reversal top") {
		return "bump_run_top"
	}
	if strings.Contains(name, "bump and run reversal bottom") {
		return "bump_run_bottom"
	}
	if strings.Contains(name, "island") && strings.Contains(name, "top") {
		return "island_top"
	}
	if strings.Contains(name, "island") && strings.Contains(name, "bottom") {
		return "island_bottom"
	}
	if strings.Contains(name, "island") {
		return "gap"
	}
	if strings.Contains(name, "pipe top") || strings.Contains(name, "horn top") {
		return "pipe_top"
	}
	if strings.Contains(name, "pipe bottom") || strings.Contains(name, "horn bottom") {
		return "pipe_bottom"
	}
	if hasAny(name, "v top", "v-top", "spike top") {
		return "v_top"
	}
	if hasAny(name, "v bottom", "v-bottom", "spike bottom") {
		return "v_bottom"
	}
	if hasAny(name, "gap", "window") {
		if inferDirection(name) == "bullish" || strings.Contains(name, "up") {
			return "gap_up"
		}
		if inferDirection(name) == "bearish" || strings.Contains(name, "down") {
			return "gap_down"
		}
		return "gap"
	}
	if hasAny(name, "false breakout", "failed breakout", "bull trap") {
		return "false_breakout"
	}
	if strings.Contains(name, "bear trap") {
		return "bear_trap"
	}
	if strings.Contains(name, "breakout") {
		return "breakout"
	}
	if strings.Contains(name, "breakdown") {
		return "breakdown"
	}
	if hasAny(name, "compression", "contraction", "squeeze", "vcp") {
		return "compression"
	}
	if hasAny(name, "expansion", "parabolic", "climax run", "squeeze breakout") {
		return "expansion"
	}
	if hasAny(name, "uptrend", "higher high", "higher low") {
		return "trend_up"
	}
	if hasAny(name, "downtrend", "lower high", "lower low") {
		return "trend_down"
	}
	if hasAny(name, "sideways") {
		return "trend_sideways"
	}
	return "generic"
}

func evidenceFor(template string) string {
	switch template {
	case "candlestick":
		return "candlestick geometry matched the named setup"
	case "indicator":
		return "indicator snapshot matched the named setup"
	case "volume":
		return "volume and spread behavior matched the named setup"
	case "fibonacci":
		return "price reacted near a Fibonacci confluence level"
	case "market_profile":
		return "OHLCV-derived TPO and volume profile matched the named auction structure"
	case "point_figure":
		return "OHLCV-derived Point & Figure box/reversal structure matched the named setup"
	default:
		return "price structure matched the named setup"
	}
}

func normalize(value string) string {
	value = strings.ToLower(value)
	value = strings.ReplaceAll(value, "-", " ")
	value = strings.ReplaceAll(value, "_", " ")
	value = strings.ReplaceAll(value, "=", " ")
	value = regexp.MustCompile(`\s+`).ReplaceAllString(value, " ")
	return strings.TrimSpace(value)
}

func hasAny(value string, needles ...string) bool {
	for _, needle := range needles {
		if strings.Contains(value, needle) {
			return true
		}
	}
	return false
}

func isToken(value, token string) bool {
	fields := strings.Fields(value)
	for _, field := range fields {
		if field == token {
			return true
		}
	}
	return false
}

func hasWord(value string, word string) bool {
	if value == word {
		return true
	}
	return strings.HasPrefix(value, word+" ") || strings.HasSuffix(value, " "+word) || strings.Contains(value, " "+word+" ")
}

func slug(value string) string {
	value = normalize(value)
	replacements := map[string]string{
		"&": "and",
		"+": "plus",
	}
	for old, next := range replacements {
		value = strings.ReplaceAll(value, old, next)
	}
	value = regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(value, "_")
	value = strings.Trim(value, "_")
	if value == "" {
		value = "pattern"
	}
	return value
}

const catalogJSON = `
{
  "kategoriler": {
    "klasik_grafik_formasyonlari": {
      "reversal_donus_formasyonlari": [
        "Head and Shoulders",
        "Inverse Head and Shoulders",
        "Complex Head and Shoulders",
        "Complex Inverse Head and Shoulders",
        "Double Top",
        "Double Bottom",
        "Triple Top",
        "Triple Bottom",
        "Rounding Top",
        "Rounding Bottom",
        "Saucer Bottom",
        "Cup and Handle",
        "Inverted Cup and Handle",
        "Adam and Eve Top",
        "Adam and Eve Bottom",
        "Eve and Adam Top",
        "Eve and Adam Bottom",
        "Broadening Top",
        "Broadening Bottom",
        "Diamond Top",
        "Diamond Bottom",
        "Island Reversal",
        "V-Top",
        "V-Bottom",
        "Spike Top",
        "Spike Bottom",
        "Bump and Run Reversal Top",
        "Bump and Run Reversal Bottom",
        "Ascending Broadening Wedge",
        "Descending Broadening Wedge",
        "Megaphone Top",
        "Megaphone Bottom",
        "Rounded Reversal",
        "Failed Breakout",
        "Bull Trap",
        "Bear Trap",
        "Quasimodo Pattern",
        "Over and Under Pattern",
        "Pipe Top",
        "Pipe Bottom",
        "Horn Top",
        "Horn Bottom",
        "Three Rising Valleys",
        "Three Falling Peaks",
        "Roof Pattern",
        "Inverted Roof Pattern"
      ],
      "continuation_devam_formasyonlari": [
        "Ascending Triangle",
        "Descending Triangle",
        "Symmetrical Triangle",
        "Bullish Symmetrical Triangle",
        "Bearish Symmetrical Triangle",
        "Rising Wedge",
        "Falling Wedge",
        "Bullish Flag",
        "Bearish Flag",
        "Bullish Pennant",
        "Bearish Pennant",
        "Rectangle",
        "Bullish Rectangle",
        "Bearish Rectangle",
        "Trading Range",
        "Consolidation Range",
        "Horizontal Channel",
        "Ascending Channel",
        "Descending Channel",
        "Price Channel",
        "Parallel Channel",
        "High Tight Flag",
        "Measured Move Up",
        "Measured Move Down",
        "Stair Step Pattern",
        "Continuation Diamond",
        "Continuation Head and Shoulders",
        "Running Triangle",
        "Wedge Continuation",
        "Cup and Handle Continuation",
        "Base Formation",
        "Flat Base",
        "Saucer with Handle",
        "Box Pattern",
        "Darvas Box",
        "Ascending Scallop",
        "Descending Scallop",
        "Inverted Ascending Scallop",
        "Inverted Descending Scallop"
      ],
      "bilateral_iki_yonlu_formasyonlar": [
        "Symmetrical Triangle",
        "Rectangle",
        "Broadening Formation",
        "Bullish Broadening Wedge",
        "Bearish Broadening Wedge",
        "Diamond Formation",
        "Pennant",
        "Wedge",
        "Channel",
        "Trading Range",
        "Inside Bar Range",
        "Coil Pattern",
        "Compression Pattern",
        "Volatility Squeeze",
        "Breakout Pattern",
        "Breakdown Pattern"
      ]
    },
    "harmonik_formasyonlar": {
      "temel_harmonik_formasyonlar": [
        "AB=CD Pattern",
        "Alternate AB=CD Pattern",
        "Gartley Pattern",
        "Bat Pattern",
        "Alternate Bat Pattern",
        "Max Bat Pattern",
        "Max Gartley Pattern",
        "Butterfly Pattern",
        "Max Butterfly Pattern",
        "Crab Pattern",
        "Deep Crab Pattern",
        "Shark Pattern",
        "Cypher Pattern",
        "5-0 Pattern",
        "Three Drives Pattern",
        "White Swan Pattern",
        "Black Swan Pattern",
        "Nen Star Pattern",
        "Leonardo Pattern",
        "Sea Pony Pattern",
        "One2One Pattern",
        "121 Pattern",
        "Anti-Gartley Pattern",
        "Anti-Bat Pattern",
        "Anti-Butterfly Pattern",
        "Anti-Crab Pattern",
        "Anti-Shark Pattern",
        "Total 1-2-3 Pattern",
        "Navarro 200 Pattern"
      ],
      "harmonik_yonleri": [
        "Bullish Gartley",
        "Bearish Gartley",
        "Bullish Bat",
        "Bearish Bat",
        "Bullish Butterfly",
        "Bearish Butterfly",
        "Bullish Crab",
        "Bearish Crab",
        "Bullish Deep Crab",
        "Bearish Deep Crab",
        "Bullish Shark",
        "Bearish Shark",
        "Bullish Cypher",
        "Bearish Cypher",
        "Bullish 5-0",
        "Bearish 5-0",
        "Bullish AB=CD",
        "Bearish AB=CD",
        "Bullish Three Drives",
        "Bearish Three Drives"
      ]
    },
    "japon_mum_candlestick_formasyonlari": {
      "tek_mum_formasyonlari": [
        "Doji",
        "Long-Legged Doji",
        "Dragonfly Doji",
        "Gravestone Doji",
        "Four Price Doji",
        "Northern Doji",
        "Southern Doji",
        "High Wave Candle",
        "Spinning Top",
        "Marubozu",
        "Bullish Marubozu",
        "Bearish Marubozu",
        "Opening Marubozu",
        "Closing Marubozu",
        "Hammer",
        "Hanging Man",
        "Inverted Hammer",
        "Shooting Star",
        "Pin Bar",
        "Bullish Pin Bar",
        "Bearish Pin Bar",
        "Takuri Line",
        "Belt Hold",
        "Bullish Belt Hold",
        "Bearish Belt Hold",
        "Long Upper Shadow",
        "Long Lower Shadow",
        "Short Body Candle",
        "Long Body Candle"
      ],
      "iki_mum_formasyonlari": [
        "Bullish Engulfing",
        "Bearish Engulfing",
        "Bullish Harami",
        "Bearish Harami",
        "Harami Cross",
        "Bullish Harami Cross",
        "Bearish Harami Cross",
        "Piercing Line",
        "Dark Cloud Cover",
        "Tweezer Top",
        "Tweezer Bottom",
        "Matching Low",
        "Matching High",
        "On-Neck Line",
        "In-Neck Line",
        "Thrusting Line",
        "Counterattack Line",
        "Bullish Counterattack",
        "Bearish Counterattack",
        "Kicking Pattern",
        "Bullish Kicking",
        "Bearish Kicking",
        "Separating Lines",
        "Bullish Separating Lines",
        "Bearish Separating Lines",
        "Meeting Lines",
        "Bullish Meeting Lines",
        "Bearish Meeting Lines",
        "Homing Pigeon",
        "Descending Hawk",
        "Stick Sandwich",
        "Doji Star",
        "Bullish Doji Star",
        "Bearish Doji Star",
        "Inside Bar",
        "Outside Bar",
        "Gapping Doji",
        "Inverted Gapping Doji"
      ],
      "uc_mum_formasyonlari": [
        "Morning Star",
        "Evening Star",
        "Morning Doji Star",
        "Evening Doji Star",
        "Abandoned Baby",
        "Bullish Abandoned Baby",
        "Bearish Abandoned Baby",
        "Three White Soldiers",
        "Three Black Crows",
        "Three Inside Up",
        "Three Inside Down",
        "Three Outside Up",
        "Three Outside Down",
        "Three Stars in the South",
        "Tri-Star",
        "Bullish Tri-Star",
        "Bearish Tri-Star",
        "Upside Gap Two Crows",
        "Two Crows",
        "Advance Block",
        "Deliberation Pattern",
        "Identical Three Crows",
        "Unique Three River Bottom",
        "Three River Morning Star",
        "Concealing Baby Swallow",
        "Ladder Bottom",
        "Stalled Pattern"
      ],
      "coklu_mum_formasyonlari": [
        "Rising Three Methods",
        "Falling Three Methods",
        "Mat Hold",
        "Rising Mat Hold",
        "Falling Mat Hold",
        "Tasuki Gap",
        "Upside Tasuki Gap",
        "Downside Tasuki Gap",
        "Side-by-Side White Lines",
        "Upside Gap Side-by-Side White Lines",
        "Downside Gap Side-by-Side White Lines",
        "Separating Candles",
        "Window",
        "Rising Window",
        "Falling Window",
        "High Price Gapping Play",
        "Low Price Gapping Play",
        "Breakaway Pattern",
        "Bullish Breakaway",
        "Bearish Breakaway",
        "Ladder Top",
        "Ladder Bottom",
        "Tower Top",
        "Tower Bottom",
        "Fry Pan Bottom",
        "Dumpling Top",
        "Three-Line Strike",
        "Bullish Three-Line Strike",
        "Bearish Three-Line Strike",
        "Three Gaps",
        "Upside Gap Three Methods",
        "Downside Gap Three Methods",
        "Two Rabbits Pattern",
        "Breaking High Signal",
        "Breaking Low Signal"
      ],
      "mum_donus_formasyonlari": [
        "Hammer",
        "Hanging Man",
        "Inverted Hammer",
        "Shooting Star",
        "Morning Star",
        "Evening Star",
        "Tower Top",
        "Tower Bottom",
        "Bullish Engulfing",
        "Bearish Engulfing",
        "Piercing Line",
        "Dark Cloud Cover",
        "Tweezer Top",
        "Tweezer Bottom",
        "Harami",
        "Harami Cross",
        "Abandoned Baby",
        "Three White Soldiers",
        "Three Black Crows",
        "Dragonfly Doji",
        "Gravestone Doji",
        "Belt Hold",
        "Kicking",
        "Counterattack",
        "Tri-Star"
      ],
      "mum_devam_formasyonlari": [
        "Rising Three Methods",
        "Falling Three Methods",
        "Mat Hold",
        "Tasuki Gap",
        "Side-by-Side White Lines",
        "Separating Lines",
        "Three-Line Strike",
        "Window",
        "Gap",
        "Breakaway",
        "High Price Gapping Play",
        "Low Price Gapping Play"
      ]
    },
    "price_action_formasyonlari": {
      "temel_price_action": [
        "Pin Bar",
        "Inside Bar",
        "Outside Bar",
        "Mother Bar",
        "Fakey Pattern",
        "Inside Bar Fakey",
        "False Breakout",
        "Failed Breakout",
        "Breakout Pullback",
        "Break and Retest",
        "Support Resistance Flip",
        "Supply Zone Rejection",
        "Demand Zone Rejection",
        "Liquidity Sweep",
        "Stop Hunt",
        "Swing Failure Pattern",
        "SFP",
        "Change of Character",
        "CHoCH",
        "Break of Structure",
        "BOS",
        "Market Structure Shift",
        "MSS",
        "Order Block",
        "Breaker Block",
        "Mitigation Block",
        "Fair Value Gap",
        "FVG",
        "Inversion FVG",
        "IFVG",
        "Imbalance",
        "Liquidity Void",
        "Equal Highs",
        "Equal Lows",
        "Higher High",
        "Higher Low",
        "Lower High",
        "Lower Low",
        "Compression",
        "Expansion",
        "Accumulation Range",
        "Distribution Range",
        "Re-accumulation",
        "Re-distribution",
        "Premium Zone",
        "Discount Zone",
        "Equilibrium Seviyesi"
      ],
      "smart_money_ict_formasyonlari": [
        "Order Block",
        "Bullish Order Block",
        "Bearish Order Block",
        "Rejection Block",
        "Propulsion Block",
        "Breaker Block",
        "Bullish Breaker",
        "Bearish Breaker",
        "Mitigation Block",
        "Fair Value Gap",
        "Balanced Price Range",
        "BPR",
        "Liquidity Sweep",
        "Buy-Side Liquidity Sweep",
        "Sell-Side Liquidity Sweep",
        "Market Structure Shift",
        "Change of Character",
        "Break of Structure",
        "Inducement",
        "IDM",
        "Internal Liquidity",
        "External Liquidity",
        "Optimal Trade Entry",
        "OTE",
        "Power of Three",
        "Accumulation Manipulation Distribution",
        "AMD Pattern",
        "Judas Swing",
        "Silver Bullet Setup",
        "Turtle Soup",
        "New York Judas Swing",
        "London Judas Swing",
        "High Resistance Liquidity Run",
        "HRLR",
        "Low Resistance Liquidity Run",
        "LRLR"
      ]
    },
    "elliott_wave_formasyonlari": {
      "dalga_yapilari": [
        "Impulse Wave",
        "Corrective Wave",
        "Motive Wave",
        "Leading Diagonal",
        "Ending Diagonal",
        "Contracting Diagonal",
        "Expanding Diagonal",
        "Zigzag Correction",
        "Flat Correction",
        "Regular Flat",
        "Expanded Flat",
        "Running Flat",
        "Triangle Correction",
        "Contracting Triangle",
        "Barrier Triangle",
        "Expanding Triangle",
        "Running Triangle",
        "Double Zigzag",
        "Triple Zigzag",
        "Double Three",
        "Triple Three",
        "WXY Correction",
        "WXYXZ Correction",
        "Irregular Correction",
        "Truncated Fifth",
        "Extended First Wave",
        "Extended Third Wave",
        "Extended Fifth Wave"
      ]
    },
    "wyckoff_formasyonlari": {
      "wyckoff_yapilari": [
        "Accumulation Schematic Type 1",
        "Accumulation Schematic Type 2",
        "Distribution Schematic Type 1",
        "Distribution Schematic Type 2",
        "Re-accumulation",
        "Re-distribution",
        "Preliminary Support",
        "PS",
        "Preliminary Supply",
        "PSY",
        "Selling Climax",
        "SC",
        "Buying Climax",
        "BC",
        "Automatic Rally",
        "AR",
        "Automatic Reaction",
        "AR Distribution",
        "Secondary Test",
        "ST",
        "Spring",
        "Upthrust",
        "Upthrust After Distribution",
        "UTAD",
        "Sign of Strength",
        "SOS",
        "Sign of Weakness",
        "SOW",
        "Last Point of Support",
        "LPS",
        "Last Point of Supply",
        "LPSY",
        "Creek",
        "Jump Across the Creek",
        "Back Up to the Creek",
        "Ice",
        "Fall Through the Ice",
        "Back Up to the Ice",
        "Absorption",
        "Cause and Effect",
        "Composite Operator"
      ]
    },
    "gap_bosluk_formasyonlari": {
      "gap_turleri": [
        "Common Gap",
        "Breakaway Gap",
        "Runaway Gap",
        "Measuring Gap",
        "Continuation Gap",
        "Exhaustion Gap",
        "Island Gap",
        "Full Gap Up",
        "Full Gap Down",
        "Partial Gap Up",
        "Partial Gap Down",
        "Tasuki Gap",
        "Upside Gap",
        "Downside Gap",
        "Window",
        "Rising Window",
        "Falling Window"
      ]
    },
    "volume_hacim_formasyonlari": {
      "hacim_tabanli_yapilar": [
        "Volume Climax",
        "Buying Climax",
        "Selling Climax",
        "Volume Dry-Up",
        "Pocket Pivot",
        "Volume Breakout",
        "Volume Expansion",
        "Volume Divergence",
        "Price Volume Divergence",
        "No Demand Bar",
        "No Supply Bar",
        "Stopping Volume",
        "Absorption Volume",
        "Effort vs Result",
        "Wide Spread Bar",
        "Narrow Spread Bar",
        "Upthrust on Volume",
        "Shakeout on Volume",
        "Accumulation Volume Pattern",
        "Distribution Volume Pattern"
      ]
    },
    "trend_kanal_formasyonlari": {
      "trend_yapilari": [
        "Uptrend",
        "Downtrend",
        "Sideways Trend",
        "Higher High Higher Low",
        "Lower High Lower Low",
        "Trendline Break",
        "Trendline Retest",
        "Ascending Channel",
        "Descending Channel",
        "Horizontal Channel",
        "Parallel Channel",
        "Regression Channel",
        "Linear Regression Channel",
        "Envelope Channel",
        "Broadening Channel",
        "Narrowing Channel",
        "Fan Lines",
        "Speed Lines",
        "Andrews Pitchfork",
        "Schiff Pitchfork",
        "Modified Schiff Pitchfork",
        "Median Line Pattern",
        "Channel Breakout",
        "Channel Breakdown"
      ]
    },
    "indicator_tabanli_formasyonlar": {
      "rsi_formasyonlari": [
        "Bullish RSI Divergence",
        "Bearish RSI Divergence",
        "Hidden Bullish RSI Divergence",
        "Hidden Bearish RSI Divergence",
        "RSI Failure Swing Top",
        "RSI Failure Swing Bottom",
        "RSI Trendline Break",
        "RSI Range Shift",
        "RSI Positive Reversal",
        "RSI Negative Reversal"
      ],
      "macd_formasyonlari": [
        "MACD Bullish Crossover",
        "MACD Bearish Crossover",
        "MACD Bullish Divergence",
        "MACD Bearish Divergence",
        "MACD Hidden Bullish Divergence",
        "MACD Hidden Bearish Divergence",
        "MACD Zero Line Cross",
        "MACD Histogram Reversal",
        "MACD Hook"
      ],
      "moving_average_formasyonlari": [
        "Golden Cross",
        "Death Cross",
        "Moving Average Crossover",
        "Price MA Breakout",
        "Price MA Breakdown",
        "MA Pullback",
        "MA Ribbon Compression",
        "MA Ribbon Expansion",
        "Moving Average Fan",
        "Moving Average Squeeze"
      ],
      "bollinger_band_formasyonlari": [
        "Bollinger Band Squeeze",
        "Bollinger Band Expansion",
        "M-Top",
        "W-Bottom",
        "Walking the Band",
        "Band Ride",
        "Mean Reversion Touch",
        "Volatility Breakout",
        "Bollinger Fakeout"
      ],
      "ichimoku_formasyonlari": [
        "Kumo Breakout",
        "Kumo Breakdown",
        "Kumo Twist",
        "Tenkan Kijun Bullish Cross",
        "Tenkan Kijun Bearish Cross",
        "Chikou Span Confirmation",
        "Kijun Bounce",
        "Cloud Support",
        "Cloud Resistance",
        "Bullish TK Cross",
        "Bearish TK Cross"
      ]
    },
    "point_and_figure_formasyonlari": {
      "p_and_f_formasyonlari": [
        "Double Top Buy Signal",
        "Double Bottom Sell Signal",
        "Triple Top Buy Signal",
        "Triple Bottom Sell Signal",
        "Bullish Catapult",
        "Bearish Catapult",
        "Bull Trap",
        "Bear Trap",
        "High Pole",
        "Low Pole",
        "Ascending Triple Top",
        "Descending Triple Bottom",
        "Spread Triple Top",
        "Spread Triple Bottom",
        "Triangle",
        "Fulcrum Pattern"
      ]
    },
    "market_profile_auction_formasyonlari": {
      "profil_yapilari": [
        "P-Shape Profile",
        "b-Shape Profile",
        "D-Shape Profile",
        "B-Shape Profile",
        "Double Distribution",
        "Single Print",
        "Poor High",
        "Poor Low",
        "Excess High",
        "Excess Low",
        "Value Area Breakout",
        "Value Area Rejection",
        "Initial Balance Breakout",
        "Initial Balance Failure",
        "Virgin Point of Control",
        "Naked POC",
        "Volume Node",
        "High Volume Node",
        "Low Volume Node"
      ]
    },
    "fibonacci_formasyonlari": {
      "fibonacci_yapilari": [
        "Fibonacci Retracement Setup",
        "Fibonacci Extension Setup",
        "Fibonacci Expansion Setup",
        "Golden Ratio Pullback",
        "61.8 Retracement",
        "78.6 Retracement",
        "88.6 Retracement",
        "127.2 Extension",
        "161.8 Extension",
        "261.8 Extension",
        "Fibonacci Cluster",
        "Fibonacci Confluence Zone",
        "Fibonacci Time Zone",
        "Fibonacci Fan",
        "Fibonacci Arc",
        "Fibonacci Spiral"
      ]
    },
    "diger_bilinen_formasyonlar": [
      "Dead Cat Bounce",
      "Blow-Off Top",
      "Selling Exhaustion",
      "Buying Exhaustion",
      "Short Squeeze",
      "Long Squeeze",
      "Climax Run",
      "Parabolic Advance",
      "Parabolic Decline",
      "Base Breakout",
      "Base Breakdown",
      "Shakeout",
      "Throwback",
      "Pullback",
      "Throwover",
      "Undercut and Rally",
      "Undercut",
      "Overthrow",
      "Failed Move",
      "Measured Move",
      "Range Expansion",
      "Range Contraction",
      "Volatility Contraction Pattern",
      "VCP",
      "Minervini Volatility Contraction Pattern",
      "Cheat Area",
      "Pivot Point Breakout",
      "Pocket Pivot",
      "Climax Top",
      "Climax Bottom",
      "Trend Exhaustion",
      "Mean Reversion Setup",
      "Squeeze Breakout",
      "Squeeze Breakdown"
    ]
  }
}
`
