package kapfinance

import (
	"testing"
	"time"
)

func TestBuildBilancoMapsKAPFactsToCanonicalFinancials(t *testing.T) {
	info, summary := BuildBilanco(BuildOptions{
		Ticker:      "TEST",
		GeneratedAt: time.Date(2026, 6, 17, 12, 0, 0, 0, time.UTC),
	}, []Fact{
		{ID: "assets", Ticker: "TEST", Period: "2025/12", LineItemNormalized: "total_assets", Value: 12_500, Currency: "TRY", Unit: "thousand_try", Confidence: 0.91, CertificationStatus: "certified", CertificationAnalysisUsable: true, SourceTableID: "tbl1", DocumentDate: "2026-02-20"},
		{ID: "equity", Ticker: "TEST", Period: "2025-Q4", LineItemNormalized: "Özkaynaklar", Value: 7_000, Currency: "TRY", Unit: "thousand_try", Confidence: 0.9, CertificationStatus: "certified", CertificationAnalysisUsable: true, SourceTableID: "tbl1", DocumentDate: "2026-02-20"},
		{ID: "revenue", Ticker: "TEST", Period: "12AB", FiscalYear: 2025, LineItemNormalized: "Hasılat", Value: 4_200, Currency: "TRY", Unit: "thousand_try", Confidence: 0.88, ValidationStatus: "valid", SourceTableID: "tbl2", DocumentDate: "2026-02-20"},
	})
	if info == nil {
		t.Fatalf("expected bilanco info, summary=%+v", summary)
	}
	if summary.FactsAccepted != 3 {
		t.Fatalf("accepted facts=%d, want 3", summary.FactsAccepted)
	}
	assertFieldValue(t, info.Data["1BL"].Years["2025"][0], 12_500_000)
	assertFieldValue(t, info.Data["2N"].Years["2025"][0], 7_000_000)
	assertFieldValue(t, info.Data["3C"].Years["2025"][0], 4_200_000)
	if info.Periods["2025-Q4"].AvailableAt == nil {
		t.Fatalf("expected conservative available_at from document date")
	}
}

func TestBuildBilancoRejectsUnresolvedPeriodAndForeignCurrency(t *testing.T) {
	info, summary := BuildBilanco(BuildOptions{Ticker: "TEST"}, []Fact{
		{ID: "bad-period", Ticker: "TEST", LineItemNormalized: "total_assets", Value: 100, Currency: "TRY", Unit: "thousand_try", Confidence: 0.9},
		{ID: "bad-currency", Ticker: "TEST", Period: "2025-Q4", LineItemNormalized: "revenue", Value: 100, Currency: "USD", Unit: "thousand_usd", Confidence: 0.9},
	})
	if info != nil {
		t.Fatalf("expected no bilanco for rejected facts")
	}
	if summary.FactsRejected != 2 {
		t.Fatalf("rejected facts=%d, want 2", summary.FactsRejected)
	}
}

func TestCanonicalLineCatalogRecognizesSPKFinancialStatementRows(t *testing.T) {
	cases := []struct {
		input      string
		code       string
		normalized string
		statement  string
	}{
		{"Satış Amaçlı Sınıflandırılan Duran Varlıklar", "1AJ", "assets_held_for_sale", StatementBalanceSheet},
		{"Özkaynak Yöntemiyle Değerlenen Yatırımların Kar/Zararlarındaki Paylar", "3HAC", "share_of_profit_loss_from_equity_method_investments", StatementIncome},
		{"Ana Ortaklık Payları", "3Z", "parent_net_income", StatementIncome},
		{"İşletme Faaliyetlerinden Kaynaklanan Nakit Akışları", "4C", "operating_cash_flow", StatementCashFlow},
		{"Peşin Ödenmiş Giderler", "", "prepaid_expenses", StatementBalanceSheet},
	}
	for _, tc := range cases {
		got, ok := CanonicalLineDefinitionForText(tc.input)
		if !ok {
			t.Fatalf("expected canonical line for %q", tc.input)
		}
		if got.Code != tc.code || got.Normalized != tc.normalized || got.StatementType != tc.statement {
			t.Fatalf("%q mapped to %+v, want code=%q normalized=%q statement=%q", tc.input, got, tc.code, tc.normalized, tc.statement)
		}
	}
}

func TestCanonicalLineCatalogUsesSectionContextForRepeatedSPKRows(t *testing.T) {
	cases := []struct {
		input      string
		context    string
		code       string
		normalized string
	}{
		{"Ticari Alacaklar", "Dönen Varlıklar", "1AC", "short_term_trade_receivables"},
		{"Ticari Alacaklar", "Duran Varlıklar", "1B", "long_term_trade_receivables"},
		{"Finansal Yatırımlar", "Dönen Varlıklar", "1AB", "short_term_financial_investments"},
		{"Finansal Yatırımlar", "Duran Varlıklar", "1BC", "long_term_financial_investments"},
		{"Ticari Borçlar", "Kısa Vadeli Yükümlülükler", "2AAGAA", "short_term_trade_payables"},
		{"Ticari Borçlar", "Uzun Vadeli Yükümlülükler", "2BBA", "long_term_trade_payables"},
		{"Ticari Alacaklar", "credit_risk_table", "", "credit_risk_trade_receivables"},
		{"Ticari Borçlar", "liquidity_risk_table", "", "liquidity_trade_payables"},
		{"Ticari Alacaklar", "fx_position_table", "", "fx_trade_receivables"},
		{"Özkaynaklar", "fx_sensitivity_table", "", "fx_sensitivity_equity_column"},
		{"Finansal Borçlar", "portfolio_limits_table", "", "portfolio_financial_debt"},
	}
	for _, tc := range cases {
		got, ok := CanonicalLineDefinitionForTextInContext(tc.input, tc.context)
		if !ok {
			t.Fatalf("expected contextual canonical line for %q in %q", tc.input, tc.context)
		}
		if got.Code != tc.code || got.Normalized != tc.normalized {
			t.Fatalf("%q in %q mapped to %+v, want code=%q normalized=%q", tc.input, tc.context, got, tc.code, tc.normalized)
		}
	}
}

func TestSPKSampleTableFieldCoverage(t *testing.T) {
	fields := []string{
		"Varlıklar",
		"Dönen Varlıklar",
		"Nakit ve Nakit Benzerleri",
		"Finansal Yatırımlar",
		"Ticari Alacaklar",
		"İlişkili Taraflardan Ticari Alacaklar",
		"İlişkili Olmayan Taraflardan Ticari Alacaklar",
		"Finans Sektörü Faaliyetlerinden Alacaklar",
		"Finans Sektörü Faaliyetleri İlişkili Taraflardan Alacaklar",
		"Finans Sektörü Faaliyetlerinden İlişkili Olmayan Taraflardan Alacaklar",
		"Diğer Alacaklar",
		"İlişkili Taraflardan Diğer Alacaklar",
		"İlişkili Olmayan Taraflardan Diğer Alacaklar",
		"Türev Araçlar",
		"Stoklar",
		"Canlı Varlıklar",
		"Peşin Ödenmiş Giderler",
		"Cari Dönem Vergisiyle İlgili Varlıklar",
		"Diğer Dönen Varlıklar",
		"Satış Amaçlı Sınıflandırılan Duran Varlıklar",
		"Toplam Dönen Varlıklar",
		"Duran Varlıklar",
		"Özkaynak Yöntemiyle Değerlenen Yatırımlar",
		"Yatırım Amaçlı Gayrimenkuller",
		"Maddi Duran Varlıklar",
		"Maddi Olmayan Duran Varlıklar",
		"Şerefiye",
		"Diğer Maddi Olmayan Duran Varlıklar",
		"Ertelenmiş Vergi Varlığı",
		"Diğer Duran Varlıklar",
		"Toplam Duran Varlıklar",
		"Toplam Varlıklar",
		"Kaynaklar",
		"Kısa Vadeli Yükümlülükler",
		"Kısa Vadeli Borçlanmalar",
		"Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları",
		"Diğer Finansal Yükümlülükler",
		"Ticari Borçlar",
		"İlişkili Taraflara Ticari Borçlar",
		"İlişkili Olmayan Taraflara Ticari Borçlar",
		"Finans Sektörü Faaliyetlerinden Borçlar",
		"Finans Sektörü Faaliyetleri İlişkili Taraflara Borçlar",
		"Finans Sektörü Faaliyetlerinden İlişkili Olmayan Taraflara Borçlar",
		"Çalışanlara Sağlanan Faydalar Kapsamında Borçlar",
		"Diğer Borçlar",
		"İlişkili Taraflara Diğer Borçlar",
		"İlişkili Olmayan Taraflara Diğer Borçlar",
		"Devlet Teşvik ve Yardımları",
		"Ertelenmiş Gelirler",
		"Dönem Karı Vergi Yükümlülüğü",
		"Kısa Vadeli Karşılıklar",
		"Çalışanlara Sağlanan Faydalara İlişkin Kısa Vadeli Karşılıklar",
		"Diğer Kısa Vadeli Karşılıklar",
		"Diğer Kısa Vadeli Yükümlülükler",
		"Satış Amaçlı Sınıflandırılan Varlık Gruplarına İlişkin Yükümlülükler",
		"Toplam Kısa Vadeli Yükümlülükler",
		"Uzun Vadeli Yükümlülükler",
		"Uzun Vadeli Borçlanmalar",
		"Uzun Vadeli Karşılıklar",
		"Çalışanlara Sağlanan Faydalara İlişkin Uzun Vadeli Karşılıklar",
		"Diğer Uzun Vadeli Karşılıklar",
		"Cari Dönem Vergisiyle İlgili Borçlar",
		"Ertelenmiş Vergi Yükümlülüğü",
		"Diğer Uzun Vadeli Yükümlülükler",
		"Toplam Uzun Vadeli Yükümlülükler",
		"Özkaynaklar",
		"Ana Ortaklığa Ait Özkaynaklar",
		"Ödenmiş Sermaye",
		"Sermaye Düzeltme Farkları",
		"Geri Alınmış Paylar",
		"Karşılıklı İştirak Sermaye Düzeltmesi",
		"Paylara İlişkin Primler/İskontolar",
		"Kar veya Zararda Yeniden Sınıflandırılmayacak Birikmiş Diğer Kapsamlı Gelirler veya Giderler",
		"Yeniden Değerleme ve Ölçüm Kazanç/Kayıpları",
		"Kar veya Zararda Yeniden Sınıflandırılacak Birikmiş Diğer Kapsamlı Gelirler veya Giderler",
		"Yabancı Para Çevirim Farkları",
		"Riskten Korunma Kazanç/Kayıpları",
		"Yeniden Değerleme ve Sınıflandırma Kazanç/Kayıpları",
		"Kardan Ayrılan Kısıtlanmış Yedekler",
		"Geçmiş Yıllar Karları/Zararları",
		"Net Dönem Karı/Zararı",
		"Kontrol Gücü Olmayan Paylar",
		"Toplam Özkaynaklar",
		"Toplam Kaynaklar",
		"Hasılat",
		"Satışların Maliyeti",
		"Ticari Faaliyetlerden Brüt Kar/Zarar",
		"Finans Sektörü Faaliyetleri Hasılatı",
		"Finans Sektörü Faaliyetleri Maliyeti",
		"Finans Sektörü Faaliyetlerinden Brüt Kâr/Zarar",
		"Brüt Kar/Zarar",
		"Genel Yönetim Giderleri",
		"Pazarlama Giderleri",
		"Araştırma ve Geliştirme Giderleri",
		"Esas Faaliyetlerden Diğer Gelirler",
		"Esas Faaliyetlerden Diğer Giderler",
		"Esas Faaliyet Karı/Zararı",
		"Yatırım Faaliyetlerinden Gelirler",
		"Yatırım Faaliyetlerinden Giderler",
		"Özkaynak Yöntemiyle Değerlenen Yatırımların Karlarından/Zararlarından Paylar",
		"Finansman Gideri Öncesi Faaliyet Kârı/Zararı",
		"Finansman Giderleri",
		"Sürdürülen Faaliyetler Vergi Öncesi Karı/Zararı",
		"Sürdürülen Faaliyetler Vergi Gideri/Geliri",
		"Dönem Vergi Gideri/Geliri",
		"Ertelenmiş Vergi Gideri/Geliri",
		"Sürdürülen Faaliyetler Dönem Karı/Zararı",
		"Durdurulan Faaliyetler Dönem Karı/Zararı",
		"Dönem Karı/Zararı",
		"Dönem Karı/Zararının Dağılımı",
		"Ana Ortaklık Payları",
		"Pay Başına Kazanç",
		"Sürdürülen Faaliyetlerden Pay Başına Kazanç",
		"Durdurulan Faaliyetlerden Pay Başına Kazanç",
		"Sulandırılmış Pay Başına Kazanç",
		"Sürdürülen Faaliyetlerden Sulandırılmış Pay Başına Kazanç",
		"Durdurulan Faaliyetlerden Sulandırılmış Pay Başına Kazanç",
		"Kar veya Zararda Yeniden Sınıflandırılmayacaklar",
		"Maddi Duran Varlıklar Yeniden Değerleme Artışları/Azalışları",
		"Maddi Olmayan Duran Varlıklar Yeniden Değerleme Artışları/Azalışları",
		"Tanımlanmış Fayda Planları Yeniden Ölçüm Kazançları/Kayıpları",
		"Özkaynak Yöntemiyle Değerlenen Yatırımların Diğer Kapsamlı Gelirinden Kar/Zararda Sınıflandırılmayacak Paylar",
		"Diğer Kar veya Zarar Olarak Yeniden Sınıflandırılmayacak Diğer Kapsamlı Gelir Unsurları",
		"Kar veya Zararda Yeniden Sınıflandırılmayacak Diğer Kapsamlı Gelire İlişkin Vergiler",
		"Kar veya Zarar Olarak Yeniden Sınıflandırılacaklar",
		"Satılmaya Hazır Finansal Varlıkların Yeniden Değerleme ve/veya Sınıflandırma Kazançları/Kayıpları",
		"Nakit Akış Riskinden Korunma Kazançları/Kayıpları",
		"Yurtdışındaki İşletmeye İlişkin Yatırım Riskinden Korunma Kazançları/Kayıpları",
		"Özkaynak Yöntemiyle Değerlenen Yatırımların Diğer Kapsamlı Gelirinden Kar/Zararda Sınıflandırılacak Paylar",
		"Diğer Kar veya Zarar Olarak Yeniden Sınıflandırılacak Diğer Kapsamlı Gelir Unsurları",
		"Kar veya Zararda Yeniden Sınıflandırılacak Diğer Kapsamlı Gelire İlişkin Vergiler Gelir/Giderler",
		"Diğer Kapsamlı Gelir",
		"Toplam Kapsamlı Gelir",
		"Toplam Kapsamlı Gelirin Dağılımı",
		"Muhasebe Politikalarındaki Değişikliklere İlişkin Düzeltmeler",
		"Hatalara İlişkin Düzeltmeler",
		"Transferler",
		"Sermaye Artırımı",
		"Temettüler",
		"Payların Geri Alım İşlemleri Nedeniyle Meydana Gelen Artış/Azalış",
		"Pay Bazlı İşlemler Nedeniyle Meydana Gelen Artış",
		"Bağlı Ortaklıklarda Kontrol Kaybı ile Sonuçlanmayan Pay Oranı Değişikliklerine Bağlı Artış/Azalış",
		"Kontrol Gücü Olmayan Pay Sahipleri ile Yapılan İşlemler",
		"Diğer Değişiklikler Nedeniyle Artış/Azalış",
		"İşletme Faaliyetlerinden Kaynaklanan Nakit Girişi Sınıfları",
		"Satılan Mallardan ve Hizmetlerden Elde Edilen Nakit Girişleri",
		"Faiz, Ücret, Prim, Komisyon ve Diğer Gelirlerden Nakit Girişleri",
		"Alım Satım Amaçlı Elde Bulundurulan Sözleşmeler ile İlgili Nakit Girişleri",
		"İşletme Faaliyetlerinden Kaynaklanan Diğer Nakit Girişleri",
		"İşletme Faaliyetlerinden Nakit Çıkışları",
		"Mal ve Hizmetler İçin Tedarikçilere Yapılan Ödemeler",
		"Faiz, Ücret, Prim, Komisyon ve Diğer Gelirlerden Nakit Çıkışları",
		"Alım Satım Amaçlı Elde Bulundurulan Sözleşmelerle İlgili Nakit Çıkışları",
		"Çalışanlara ve Çalışanlar Adına Yapılan Ödemelerden Kaynaklanan Nakit Çıkışları",
		"İşletme Faaliyetlerinden Kaynaklanan Diğer Nakit Çıkışları",
		"Faaliyetlerden Net Nakit Akışları",
		"Ödenen Temettüler",
		"Alınan Temettüler",
		"Ödenen Faiz",
		"Alınan Faiz",
		"Vergi Ödemeleri/İadeleri",
		"Diğer Nakit Girişleri/Çıkışları",
		"Bağlı Ortaklıkların Kontrolünün Kaybı Sonucunu Doğuracak Satışlara İlişkin Nakit Girişleri",
		"Bağlı Ortaklıkların Kontrolünün Elde Edilmesine Yönelik Alışlara İlişkin Nakit Çıkışları",
		"Başka İşletmelerin veya Fonların Paylarının veya Borçlanma Araçlarının Satılması Sonucu Elde Edilen Nakit Girişleri",
		"Başka İşletmelerin veya Fonların Paylarının veya Borçlanma Araçlarının Edinimi İçin Yapılan Nakit Çıkışları",
		"Maddi ve Maddi Olmayan Duran Varlıkların Satışından Kaynaklanan Nakit Girişleri",
		"Maddi ve Maddi Olmayan Duran Varlıkların Alımından Kaynaklanan Nakit Çıkışları",
		"Diğer Uzun Vadeli Varlıkların Satışından Kaynaklanan Nakit Girişleri",
		"Diğer Uzun Vadeli Varlık Alımlarından Nakit Çıkışları",
		"Verilen Nakit Avans ve Borçlarlar",
		"Verilen Nakit Avans ve Borçlardan Geri Ödemeler",
		"Türev Araçlardan Nakit Çıkışları",
		"Türev Araçlardan Nakit Girişleri",
		"Devlet Teşviklerinden Elde Edilen Nakit Girişleri",
		"Pay ve Diğer Özkaynağa Dayalı Araçların İhracından Kaynaklanan Nakit Girişleri",
		"İşletmenin Kendi Paylarını ve Diğer Özkaynağa Dayalı Araçlarını Almasıyla İlgili Nakit Çıkışları",
		"Borçlanmadan Kaynaklanan Nakit Girişleri",
		"Borç Ödemelerine İlişkin Nakit Çıkışları",
		"Finansal Kiralama Sözleşmelerinden Kaynaklanan Borç Ödemelerine İlişkin Nakit Çıkışları",
		"Yabancı Para Çevrim Farklarının Nakit ve Nakit Benzerleri Üzerindeki Etkisi",
		"Dönem Başı Nakit ve Nakit Benzerleri",
		"Dönem Sonu Nakit ve Nakit Benzerleri",
		"Dönem Net Karı/Zararı Mutabakatı ile İlgili Düzeltmeler",
		"Amortisman ve İtfa Gideri ile İlgili Düzeltmeler",
		"Değer Düşüklüğü/İptali ile İlgili Düzeltmeler",
		"Karşılıklar ile İlgili Düzeltmeler",
		"Faiz Gelirleri ve Giderleri ile İlgili Düzeltmeler",
		"Gerçekleşmemiş Yabancı Para Çevirim Farkları ile İlgili Düzeltmeler",
		"Pay Bazlı Ödemeler ile İlgili Düzeltmeler",
		"Gerçeğe Uygun Değer Kayıpları/Kazançları ile İlgili Düzeltmeler",
		"İştiraklerin Dağıtılmamış Karları ile İlgili Düzeltmeler",
		"Vergi Gideri/Geliri ile İlgili Düzeltmeler",
		"Duran Varlıkların Elden Çıkarılmasından Kaynaklanan Kayıp/Kazançlar ile İlgili Düzeltmeler",
		"Yatırım ya da Finansman Faaliyetlerinden Kaynaklanan Nakit Akışlarına Neden Olan Diğer Kalemlere İlişkin Düzeltmeler",
		"Kar/Zarar Mutabakatı ile İlgili Diğer Düzeltmeler",
		"İşletme Sermayesinde Gerçekleşen Değişimler",
		"Stoklardaki Artış/Azalışla İlgili Düzeltmeler",
		"Ticari Alacaklardaki Artış/Azalışla İlgili Düzeltmeler",
		"Finans Sektörü Faaliyetlerinden Alacaklarda Artış/Azalış",
		"Faaliyetlerle İlgili Diğer Alacaklardaki Artış/Azalışla İlgili Düzeltmeler",
		"Ticari Borçlardaki Artış/Azalışla İlgili Düzeltmeler",
		"Finans Sektörü Faaliyetlerinden Borçlardaki Artış/Azalış",
		"Faaliyetlerle İlgili Diğer Borçlardaki Artış/Azalışla İlgili Düzeltmeler",
		"İşletme Sermayesinde Gerçekleşen Diğer Artış/Azalışla İlgili Düzeltmeler",
		"Şirket Tarafından Verilen TRİ’ler",
		"Kendi Tüzel Kişiliği Adına Vermiş Olduğu TRİ’lerin Toplam Tutarı",
		"Tam Konsolidasyon Kapsamına Dahil Edilen Ortaklıklar Lehine Vermiş Olduğu TRİ’lerin Toplam Tutarı",
		"Olağan Ticari Faaliyetlerinin Yürütülmesi Amacıyla Diğer 3. Kişilerin Borcunu Temin Amacıyla Vermiş Olduğu TRİ’lerin Toplam Tutarı",
		"Diğer Verilen TRİ’lerin Toplam Tutarı",
		"Ana Ortak Lehine Vermiş Olduğu TRİ’lerin Toplam Tutarı",
		"B ve C maddeleri Kapsamına Girmeyen Diğer Grup Şirketleri Lehine Vermiş Olduğu TRİ’lerin Toplam Tutarı",
		"C Maddesi Kapsamına Girmeyen 3. Kişiler Lehine Vermiş Olduğu TRİ’lerin Toplam Tutarı",
		"Raporlama tarihi itibariyle maruz kalınan azami kredi riski",
		"Azami riskin teminat, vs ile güvence altına alınmış kısmı",
		"Vadesi geçmemiş ya da değer düşüklüğüne uğramamış finansal varlıkların net defter değeri",
		"Vadesi geçmiş ancak değer düşüklüğüne uğramamış varlıkların net defter değeri",
		"Değer düşüklüğüne uğrayan varlıkların net defter değerleri",
		"Vadesi geçmiş brüt defter değeri",
		"Net değerin teminat, vs ile güvence altına alınmış kısmı",
		"Finansal durum tablosu dışı kredi riski içeren unsurlar",
		"Vadesi üzerinden 1-30 gün geçmiş",
		"Vadesi üzerinden 1-3 ay geçmiş",
		"Vadesi üzerinden 3-12 ay geçmiş",
		"Vadesi üzerinden 1-5 yıl geçmiş",
		"Vadesini 5 yıldan fazla geçmiş",
		"Sözleşme uyarınca vadeler",
		"Beklenen Vadeler",
		"Defter Değeri",
		"Sözleşme uyarınca nakit çıkışlar toplamı",
		"Beklenen nakit çıkışlar toplamı",
		"Türev Olmayan Finansal Yükümlülükler",
		"Banka kredileri",
		"Borçlanma senedi ihraçları",
		"Finansal kiralama yükümlülükleri",
		"Türev Finansal Yükümlülükler Net",
		"Türev Nakit Girişleri",
		"Türev Nakit Çıkışları",
		"Alacaklar",
		"Bankalardaki Mevduat",
		"Mevduat",
		"Finansal Araçlar",
		"Finansal Varlıklar",
		"Parasal Finansal Varlıklar",
		"Parasal Olmayan Finansal Varlıklar",
		"Finansal Yükümlülükler",
		"Parasal Olan Diğer Yükümlülükler",
		"Parasal Olmayan Diğer Yükümlülükler",
		"Toplam Yükümlülükler",
		"Net Yabancı Para Varlık / Yükümlülük Pozisyonu",
		"Parasal Kalemler Net Yabancı Para Varlık / Yükümlülük Pozisyonu",
		"Döviz Hedge'i İçin Kullanılan Finansal Araçların Toplam Gerçeğe Uygun Değeri",
		"Döviz Varlıkların Hedge Edilen Kısmının Tutarı",
		"Döviz Yükümlülüklerin Hedge Edilen Kısmının Tutarı",
		"ABD Doları net varlık/yükümlülüğü",
		"ABD Doları riskinden korunan kısım",
		"ABD Doları Net Etki",
		"ABD Doları kurunun % değişmesi halinde",
		"Avro net varlık/yükümlülüğü",
		"Avro riskinden korunan kısım",
		"Avro Net Etki",
		"Avro kurunun % değişmesi halinde",
		"Diğer döviz net varlık/yükümlülüğü",
		"Diğer döviz kuru riskinden korunan kısım",
		"Diğer Döviz Varlıkları Net Etki",
		"Diğer döviz kurlarının ortalama % değişmesi halinde",
		"Döviz Kuru Duyarlılık Analizi Tablosu",
		"Cari Dönem",
		"Önceki Dönem",
		"Kar/Zarar",
		"Özkaynaklar",
		"Yabancı paranın değer kazanması",
		"Yabancı paranın değer kaybetmesi",
		"TOPLAM (3+6+9)",
		"Sabit faizli finansal araçlar",
		"Değişken faizli finansal araçlar",
		"Gerçeğe uygun değer farkı kar/zarara yansıtılan varlıklar",
		"Satılmaya hazır finansal varlıklar",
		"Para ve Sermaye Piyasası Araçları",
		"Gayrimenkuller, Gayrimenkule Dayalı Projeler, Gayrimenkule Dayalı Haklar",
		"İştirakler",
		"İlişkili Taraflardan Alacaklar Ticari Olmayan",
		"Diğer Varlıklar",
		"Diğer Kaynaklar",
		"Para ve Sermaye Piyasası Araçlarının 3 yıllık Gayrimenkul Ödemeleri İçin Tutulan Kısmı",
		"Vadeli/Vadesiz TL/Döviz",
		"Yabancı Sermaye Piyasası Araçları",
		"Yabancı Gayrimenkuller, Gayrimenkule Dayalı Projeler, Gayrimenkule Dayalı Haklar",
		"Atıl Tutulan Arsa/Araziler",
		"Yabancı İştirakler",
		"İşletmeci Şirkete İştirak",
		"Gayrinakdi Krediler",
		"Üzerinde proje geliştirilecek mülkiyeti ortaklığa ait olmayan ipotekli arsaların ipotek bedelleri",
		"Borçlanma Sınırı",
		"Portföy Sınırlamaları",
		"Finansal Tablo ve Dipnot Formatları Hakkında Duyuru",
		"Finansal Durum Tablosu",
		"Bilanço",
		"Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu",
		"Kar veya Zarar Tablosu",
		"Kar veya Zarar Kısmı",
		"Diğer Kapsamlı Gelir Tablosu",
		"Diğer Kapsamlı Gelirler",
		"Özkaynaklar Değişim Tablosu",
		"Nakit Akış Tablosu",
		"Dipnot Referansları",
		"Geçmiş Dönemi",
		"Ara Toplam",
		"Toplam Dönen Varlıklar",
		"Toplam Duran Varlıklar",
		"Toplam Kısa Vadeli Yükümlülükler",
		"Toplam Uzun Vadeli Yükümlülükler",
		"Toplam Kaynaklar",
		"Diğer Maddi Olmayan Duran Varlıklar",
		"Diğer Kazanç/Kayıplar",
		"Durdurulan Faaliyetlerden Gelirler",
		"Durdurulan Faaliyetlerden Giderler",
		"Durdurulan faaliyetler vergi öncesi kârı/zararı",
		"Durdurulan Faaliyetler Vergi Gideri/Geliri",
		"Kar veya Zararda Yeniden Sınıflandırılmayacak Birikmiş Diğer Kapsamlı Gelirler ve Giderler",
		"Kar veya Zararda Yeniden Sınıflandırılacak Birikmiş Diğer Kapsamlı Gelirler ve Giderler",
		"Birikmiş Karlar",
		"Pay İhraç Primleri/İskontoları",
		"Yeniden Değerleme ve Ölçüm Kazanç / Kayıpları",
		"Riskten Korunma Kazanç / Kayıpları",
		"Yeniden Değerleme ve Sınıflandırma Kazanç / Kayıpları",
		"Geçmiş Yıllar Kar / Zararları",
		"Net Dönem Karı / Zararı",
		"İşletme Faaliyetlerden Nakit Akışları",
		"Vergi Ödemeleri/İadeler",
		"Vergi Ödemeler/İadeler",
		"Yabancı Para Çevirim Farklarının Etkisinden Önce Nakit ve Nakit Benzerlerindeki Net Artış/Azalış",
		"Finansal Araçlardan Kaynaklanan Risklerin Niteliği ve Düzeyi",
		"Kredi Riski Açıklamaları",
		"Finansal Araç Türleri İtibariyle Maruz Kalınan Kredi Riskleri",
		"TFRS 7 referansı",
		"TFRS 7 referasnsı",
		"İlişkili Taraf",
		"Diğer Taraf",
		"Likidite Riskine İlişkin Açıklamalar",
		"Likidite Riski Açıklamaları",
		"Sözleşme uyarınca nakit çıkışlar",
		"Sözleşme uyarınca/Beklenen nakit çıkışlar toplamı",
		"3 aydan kısa",
		"3-12 ay arası",
		"1-5 yıl arası",
		"5 yıldan uzun",
		"1-2 yıl arası",
		"2 yıldan uzun",
		"Beklenen (veya sözleşme uyarınca) vadeler",
		"Diğer borçlar",
		"Piyasa Riski Açıklamaları",
		"Döviz Pozisyonu Tablosu",
		"Türk Lirası Karşılığı",
		"Tük Lirası Karşılığı",
		"Fonksiyonel para birimi",
		"ABD Doları",
		"Avro",
		"Yen",
		"GBP",
		"Diğer Döviz",
		"Dönen Varlıklar (1+2+3)",
		"Duran Varlıklar (5+6+7)",
		"Toplam Varlıklar (4+8)",
		"Kısa Vadeli Yükümlükler (10+11+12)",
		"Uzun Vadeli Yükümlülükler (14+15+16)",
		"Toplam Yükümlülükler (13+17)",
		"Finansal durum tablosu Dışı Döviz Cinsinden Türev Araçların Net Varlık / Yükümlülük Pozisyonu",
		"Aktif Karakterli Finansal durum tablosu Dışı Döviz Cinsinden Türev Ürünlerin Tutarı",
		"Pasif Karakterli Finansal durum tablosu Dışı Döviz Cinsinden Türev Ürünlerin Tutarı",
		"Faiz Pozisyonu Tablosu",
		"Diğer Risklere İlişkin Duyarlılık Analizi",
		"Finansal Araçlar Gerçeğe Uygun Değer Açıklamaları ve Finansal Riskten Korunma Muhasebesi Çerçevesindeki Açıklamalar",
		"Raporlama Döneminden Sonraki Olaylar",
		"Finansal tabloların önemli ölçüde etkileyen ya da finansal tabloların açık, yorumlanabilir ve anlaşılabilir olması açısından açıklanması gereken diğer hususlar",
		"Ek Dipnot: Portföy Sınırlamalarına Uyumun Kontrolü",
		"Portföy Sınırlamalarına Uyumun Kontrolü",
		"Konsolide Olmayan (Bireysel) Finansal Tablo Ana Hesap Kalemleri",
		"Konsolide Olmayan (Bireysel) Diğer Finansal Bilgiler",
		"İlgili Düzenleme",
		"Asgari/Azami Oran",
		"Toplam Varlıklar (Aktif Toplamı)",
		"Finansal Borçlar",
		"Finansal Kiralama Borçları",
		"İlişkili Taraflara Borçlar (Ticari Olmayan)",
		"Yabancı Gayrimenkuller, Gayrimenkule Dayalı Projeler, Gayrimenkule Dayalı Haklar, İştirakler, Sermaye Piyasası Araçları",
	}
	missing := []string{}
	for _, field := range fields {
		if _, ok := CanonicalLineDefinitionForText(field); !ok {
			missing = append(missing, field)
		}
	}
	if len(missing) > 0 {
		t.Fatalf("SPK sample fields are not covered by canonical catalog: %+v", missing)
	}
}

func assertFieldValue(t *testing.T, value *float64, want float64) {
	t.Helper()
	if value == nil {
		t.Fatalf("field value is nil, want %.0f", want)
	}
	if *value != want {
		t.Fatalf("field value=%.0f, want %.0f", *value, want)
	}
}
